### ISSUE TITLE
Back button margin hard-coded to 13 on Android

### ISSUE THREAD

**Issue by scarlac** [react-navigation/stack#120]
### Current Behavior

react-navigation-stack renders back buttons wrapped with hardcoded styles on Android. iOS is not affected.
Caused by:
https://github.com/react-navigation/react-navigation-stack/blob/9126e2993836656e259f849d739a69b5d3a2c8ed/src/views/Header/HeaderBackButton.js#L141
If a developer wants to align back button image to the content of the rest of the app it currently requires platform specific code, specifically coded against iOS having 0 margin and Android having 13 px margin.

### Expected Behavior

No hard-coded horizontal margin should be applied, it should be configurable, or at least documented.

### How to reproduce

Set `navigationOptions.headerBackImage = <Text>Foo</Text>`. Render on iOS. Render on Android. Compare results - one platform will be pushed 13 pixels in while another will not. Issue can be reproduced fully under normal conditions.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.3.2
| react-native     | 0.58.6
| node             | 11.2.0
| npm or yarn      | 1.13.0

**Comment by satya164** [comment]
I'll think about exporting the base components in a more re-usable way.

**Comment by olistic** [comment]
Hello! Did anything change since you guys had this conversation? Would you accept a PR that moves the margin from the wrapper to the `icon` style?
