### ISSUE TITLE
Flickering when using custom header with non standard height

### ISSUE THREAD

**Issue by joel-bitar** [react-navigation/stack#123]
### Current Behavior

I have a StackNavigator with a custom header component with a non standard height (150 in the example). When navigating to the StackNavigator from a SwitchNavigator there is flickering where the screen is first rendered behind the header. I created a simple snack reproducing the issue: https://snack.expo.io/@bennyb/flickering
However it seems like it's hard to reproduce in the snack, probably because the views are simple an quick to render. But this is very noticable in the app we are currently developing where the views are a bit more complex.

It seems occur due to `getDefaultHeaderHeight` in react-navigation-stack (`views/StackView/StackViewLayout.js`) which seems to assume some header heights. I tested changing the height returned by it and it seems to resolve the problem

### Expected Behavior

I expect the header to have the correct height before measuring taking place in StackViewLayout. Maybe it should be possible to define custom default heights for the header which the StackViewLayout can default to before it has measured the correct height.

### How to reproduce

The yellow is the header and the red is the screen in the StackNavigator. Notice how the screen is partly rendered behind the header at first.

![glitch](https://user-images.githubusercontent.com/14925799/52861064-99806d80-3131-11e9-8ef2-81212c73d7fe.gif)

Here is a snack reproducing the issue, but it's hard to see since the emulator seems to be quick. But navigating back and forth a couple of time will trigger it :)
https://snack.expo.io/@bennyb/flickering

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.2.3
| react-native     | 0.57.0
| node             | 10.15.0
| npm or yarn      | npm

**Comment by egemenkayalidere** [comment]
...
import {Header} from 'react-navigation';
...

static navigationOptions = (props) => ({
        header: null,
        headerStyle: {
            height: Header.HEIGHT,
        }
});

Above code, attention to headerStyle height value. Even you use header property as null, do not forget to point headerStyle height value. Then, when you go back to another screen, there will be no flickering because the height values will be same.

I hope this solution will be help for yours problem.

**Comment by mikaoelitiana** [comment]
Is this not fixed by PR @sophister mentionned?

**Comment by nihp** [comment]
Any solution for this issue?

**Comment by JarnoNijhof** [comment]
You can try adding a z-index to overlap the header mayby?

**Comment by nihp** [comment]
But I don't want to overlap the screen. I need to restrict flickering.

Answer for Header with zIndex and Header in a github question https://github.com/react-navigation/react-navigation/issues/3576#issuecomment-368111892

**Comment by JarnoNijhof** [comment]
When the gif reloads, I see an darkyellow header. (u means that with flickering)
Does it mean that you have two headerrs?

Then you can try this;

```
export const CustomNavigator = createStackNavigator({
     Home: {
          screen: HomeScreen,
          navigationOptions: ({navigation}) => ({
               title: 'Home',
               header: null,
          }),
     },
});
```

**Comment by nihp** [comment]
Yes, I am navigating from the footer Icon to the header Icon.

So while I am showing the Footer the Title is Home and While I am click on the right element. It shows the header title as New Updates. Refer my code https://github.com/react-navigation/react-navigation/issues/6448

**Comment by JarnoNijhof** [comment]
ah complex... mayby it's not loaded correctly.
You can try something like this mayby;

```
export const LoadingPage = () =>  {
    componentDidMount(){
         // When the page is loaded it starts counting
         this.timeoutHandle = setTimeout(()=>{
         }, 1000);
    }
};
```

**Comment by ospfranco** [comment]
I've tried @egemenkayalidere solution, but it doesn't seem to be working, I can still see the flickering, is there any other workaround, otherwise I will just use patch-package to change the `getDefaultHeaderHeight` function

**Comment by ospfranco** [comment]
The issue is still hapenning however I've managed to get around by setting a fixed header height
