### ISSUE TITLE
Transparent header hides buttons on android when headerMode=float

### ISSUE THREAD

**Issue by erandagan** [react-navigation/stack#126]
Related to https://github.com/react-navigation/react-navigation/issues/4612

### Current Behavior
Setting `headerTransparent` to `true` when `headerMode` is set to `float` hides the back button on Android, similar to the the issue linked above. When `headerMode` is `screen`, everything works as it should.

### Expected Behavior
The header should be transparent with it's buttons still visible.

### How to reproduce
- Use any android device
- Create a stack navigator with headerMode set to `float`.
- On an internal screen which should include a back button, set `headerTransparent` to `true`
- The back button will not be visible
- Set `headerMode` to `screen`
- Everything works correctly

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.11.2
| react-native     | 0.56
| node             | 10.8.0
| npm or yarn      | yarn 1.9.2

**Comment by satya164** [comment]
This shouldn't happen in latest alpha. Please let me know if this is still happening.

**Comment by MatthieuLemoine** [comment]
@satya164 Can the alpha version be used with react-navigation latest release ? https://github.com/react-navigation/react-navigation/releases/tag/3.11.1
