### ISSUE TITLE
GestureHandler already initialized for root view

### ISSUE THREAD

**Issue by ethantran** [react-navigation/stack#136]
I will occasionally get this error, but I am not sure how to reproduce it. All I know is that it is related to the stack navigator and how it implements react native gesture handler. When I switch it to another navigator like bottom tab, it does not throw error. I can only prevent the error temporarily by closing the app and opening it back up.

Platform: Android
```
"react": "16.8.3",
"react-native": "0.59.5",
"react-native-gesture-handler": "^1.2.1",
"react-navigation": "3.9.1"
```

```
const MainNavigator = createBottomTabNavigator({
  Home: {
    screen: HomeScreen
  }
});
export const AppContainer = createAppContainer(MainNavigator);
```

**Comment by satya164** [comment]
Closing due to no repro. If this still occurs with the latest versions, please open a new issue with a repro.

**Comment by AilsonFreire** [comment]
I am having the same problem. I don´t know why.

**Comment by Nagibaba** [comment]
I restarted Metro Bundler. Error gone

**Comment by SwordElucidator** [comment]
Any update?

**Comment by mikebouwmans** [comment]
I have this error aswell at random times. Cant seem te reproduce it.

**Comment by yaghami** [comment]
Just try close and reopening the app. Solved for me.

**Comment by angel-luis** [comment]
Same here, after restart Expo the error gone. I didn't touch the code.

Just developing a starter project with latest RN and RNN@next.

**Comment by web-2017** [comment]
just restart your app on device, Metro Bundler, error should gone
