### ISSUE TITLE
Is the typescript types for createStackNavigator correct? 

### ISSUE THREAD

**Issue by seanyu4296** [react-navigation/stack#138]
Correct me if i'm wrong since i am new to react-navigation codebase, but based on my observation `NavigationStackOptions` type that is used by `createStackNavigator` does not have the properties such as `initialRouteName`, `initialRouteParams`, `mode` and etc. is this the intended code or it's legitimately lacking?

https://reactnavigation.org/docs/en/stack-navigator.html#stacknavigatorconfig
https://github.com/react-navigation/stack/blob/c141c24a12c5969ac5864dbceba04afa9e9c7917/src/types.tsx#L118
https://github.com/react-navigation/stack/blob/c141c24a12c5969ac5864dbceba04afa9e9c7917/src/navigators/createStackNavigator.tsx#L7

**Comment by satya164** [comment]
`initialRouteName` and `initialRouteParams` come from the router. But we don't have proper types for `@react-navigation/core` yet, so it's incomplete.

**Comment by satya164** [comment]
They should be correct as of v4

**Comment by seanyu4296** [comment]
Thanks! @satya164 i'll check it out soon
