### ISSUE TITLE
Improper accessibility tags trap user on some elements

### ISSUE THREAD

**Issue by Nigh7Sh4de** [react-navigation/stack#15]
When VoiceOver is enabled on iOS, the operating system only allows the user to navigate through elements that have `accessible={true}`. This also means that elements which should not be interactive that are given the `accessible={true}` tag, can potentially trap or completely disable the user. I have created a couple PRs to fix some of these issues.

**Comment by Nigh7Sh4de** [comment]
#13 removes an accessible tag which disables entire screens
#14 removes accessible tags which trap the user in the navbar

**Comment by satya164** [comment]
Since we're talking about accessibility, it'll also be nice to add the new `accessibilityRole` props.

**Comment by Nigh7Sh4de** [comment]
Yeah absolutely! Which elements do you feel need to have the `accessibilityRole` added?

**Comment by satya164** [comment]
Closing as both PRs were merged
