### ISSUE TITLE
How to mount all screens on App load

### ISSUE THREAD

**Issue by trevorwhealy** [react-navigation/stack#150]
Hello, I have a simple Application with 3 simple RN `WebView` screens.

To avoid the page loading of each WebView as the user progresses through the stack, I would like to mount each Screen at app load time, similar to how [React Native Navigation by Wix](https://github.com/wix/react-native-navigation) does. 

I would use Wix's stack navigator implementation, but I prefer the API of this library, it's truly perfect. I understand why this library might not have this functionality implemented by default for performance reasons, but I was wondering if this was at all possible to achieve. 

Any help immensely appreciated, and thank you for the great work on this lib!

```
createStackNavigator({
  PageOne: WebView1, // mounts on app load
  PageTwo: WebView2, // PROBLEM: mounts only when navigated to
  PageThree: WebView3 // PROBLEM: mounts only when navigated to
})
```

**Comment by satya164** [comment]
I already replied to you here https://github.com/react-navigation/react-navigation/issues/6010#issuecomment-503751540

We may eventually add a method to preload a screen before navigating to it, but it's not the same as always pre-rendering all screens.

https://github.com/react-navigation/rfcs/issues/73

**Comment by trevorwhealy** [comment]
@satya164 thanks, that's effectively what I would like to achieve!
