### ISSUE TITLE
[Bug][iOS] Slow on simulator

### ISSUE THREAD

**Issue by kesha-antonov** [react-navigation/stack#163]
Hey! Nice update with animations
However its slow when app runs in simulator
If remote debugging turned on - transitions fast

**Comment by satya164** [comment]
Thanks for the report. What do you mean by slow? Is the animation running slowly or which part is slow? Can you post a video?

**Comment by kesha-antonov** [comment]
@satya164 
Ahh sorry
Animations is fine
I just see delay 4-5 seconds between when I press touchable and transition to the next scene
And 2 seconds between when I press back button and transition to prev scene

Here's video
It didn't capture mouse click 

https://drive.google.com/file/d/1jAxK7ntMFxc3puP_0MLDgv5owKvdtvbE/view?usp=sharing

**Comment by satya164** [comment]
Thanks! I can see a delay (not as long as 4-5 seconds though) and it's a known issue: https://github.com/react-navigation/stack/issues/162

I'm closing the issue since we're tracking it there.

**Comment by kesha-antonov** [comment]
Ok, thanks for the reply!
Yeah, its not visible on video. I counted it
