### ISSUE TITLE
Complete transition never called when view is starting to animate and then immediately unmounted

### ISSUE THREAD

**Issue by Sergeeeek** [react-navigation/stack#173]
We have code that depends on `isTransitioning` properties in navigation state.

Sometimes when some navigation action is dispatched (e.g. `goBack()`) and then `StackNavigator` gets quickly unmounted COMPLETE_TRANSITION action is never dispatched.

I think this case is handled by this code: https://github.com/react-navigation/stack/blob/ee241aacd5dab42e27302df78f0cef8a43d99126/src/views/Stack/Card.tsx#L385-L392

But it doesn't work sometimes, I assume it's because `isRunningAnimation` is updated asynchronously from `react-reanimated` here: https://github.com/react-navigation/stack/blob/ee241aacd5dab42e27302df78f0cef8a43d99126/src/views/Stack/Card.tsx#L197-L201

This means that it's possible to unmount the view before this callback has a chance to fire leading to this bug.

**Comment by satya164** [comment]
Hey! I would suggest to move away from using `isTransitioning`. We're planning to remove this property.

cc @ericvicenti

**Comment by Sergeeeek** [comment]
I would love to, but we need to block all user actions while there is a transition in progress.

Is there any way to do that without `isTransitioning`?

**Comment by satya164** [comment]
Stack navigator should already prevent user actions during the transition. Is it not working for you?

**Comment by Sergeeeek** [comment]
No, it lets me press on buttons from the previous screen while transition is in progress.

Also in my case `StackNavigator` is nested in a `BottomTabNavigator`, so even if it would block the previous screen it wouldn't block `BottomTabNavigator`, right?

**Comment by satya164** [comment]
> No, it lets me press on buttons from the previous screen while transition is in progress.

What version are you on? I'll look into it.

> Also in my case StackNavigator is nested in a BottomTabNavigator, so even if it would block the previous screen it wouldn't block BottomTabNavigator, right?

It wouldn't. But what's the reason you want to block it?

**Comment by Sergeeeek** [comment]
> What version are you on? I'll look into it.

Just updated to 3.11.0, issue is still present. Small clarification: it does prevent me from opening the same screen twice (navigation actions are idempotent), but not from opening multiple different screens while transitioning.

> It wouldn't. But what's the reason you want to block it?

I don't have a choice on this matter, that's a requirement for my app. I guess it's to prevent the user from accidentally tapping multiple things. Arguably not a good idea, but I have to work with it.

Btw, thank you for very quick support.

**Comment by Sergeeeek** [comment]
Here is a gif reproducing the issue.
![bug](https://user-images.githubusercontent.com/3381399/62276584-0d4ad400-b44d-11e9-8a90-486fda49b682.gif)
