### ISSUE TITLE
V1 & V2 android platform jump back without animation when pan gesture end

### ISSUE THREAD

**Issue by gaodeng** [react-navigation/stack#177]
```js
transitionConfig: () =>StackViewTransitionConfigs.SlideFromRightIOS,
gesturesEnabled: true,
gestureResponseDistance: {
    horizontal: Dimensions.get('window').width,
 },
```

Not every time this problem occurs, but there is at least a 50% chance that this problem will occur.

**Comment by gaodeng** [comment]
here is a video showing the bug.
https://www.youtube.com/watch?v=QJHNFIV3WzU

**Comment by Matergi** [comment]
i have the same bug

**Comment by satya164** [comment]
Can you repro this with latest stable version?

**Comment by satya164** [comment]
Closing due to no response
