### ISSUE TITLE
Getting error after import {CreateStackNavigator} from 'react-navigation-stack'

### ISSUE THREAD

**Issue by ctopher7** [react-navigation/stack#182]
the error says : undefined is not an object (evaluation '_core.ThemeColors.light') 

on file: StackViewCard.js 

i already checked the file, and there is a backgroundColor using ThemeColors.light.body from @react-navigation/core

**Comment by domene96** [comment]
Same issue here

**Comment by IjzerenHein** [comment]
Which version are you using?

**Comment by domene96** [comment]
Am attempting to upgrade dependencies to sdk 32 from 25

{
  "name": "___",
  "version": "___",
  "private": true,
  "devDependencies": {
    "babel-plugin-module-resolver": "^3.2.0",
    "jest-expo": "^32.0.0",
    "react-test-renderer": "16.5.0"
  },
  "main": "App.js",
  "scripts": {
    "start": "expo start",
    "eject": "expo eject",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^32.0.0",
    "firebase": "^6.4.0",
    "react": "16.5.0",
    "react-native": "0.57.1",
    "react-native-communications": "^2.2.1",
    "react-native-datepicker": "^1.6.0",
    "react-native-easy-grid": "^0.2.0",
    "react-native-fast-image": "^4.0.12",
    "react-native-fcm": "^14.1.3",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-image-zoom-viewer": "^2.0.20",
    "react-native-lightbox": "^0.8.0",
    "react-native-reanimated": "^1.2.0",
    "react-navigation": "^3.11.1",
    "react-navigation-stack": "^1.4.0-alpha.0",
    "uuid": "^3.2.1"
  }
}

**Comment by IjzerenHein** [comment]
Could you try installing `react-navigation-stack@1.4.0` ?

**Comment by domene96** [comment]
I do have it installed. Re-ran the app and now it is printing a different error.

(0, _reactNavigationStack.createAppContainer) is not a function (ln (´0, _reactNavigationStack.createAppContainer)', '(0, _reactNavigationStack.createAppContainer)' is undefined)

I was using StackNavigator and am now attempting to use createStackNavigator.

**Comment by adamsolomon1986** [comment]
I'm getting the same error after updating to Expo 34? any updates on this?

**Comment by ofgowtham** [comment]
I tried removing node_modules and re-installing them. It worked.

**Comment by ctopher7** [comment]
@ian-smithh thank you so much!

**Comment by ltsharma** [comment]
@ian-smithh Thanks it worked. hate to edit node modules though. it cant be changed in plugin itself?

**Comment by ian-smithh** [comment]
@ltsharma I agree, editing node modules isn't really sustainable. I'm not familiar with how Node.js packaging works but I might look at it over the weekend if I have time.

**Comment by mustivar** [comment]
upgrading @react-navigation/core to latest version fixed it for me.

**Comment by ian-smithh** [comment]
@ctopher7 can you confirm? I will try later with the updated version as well.

**Comment by ayushagarwalk** [comment]
@ian-smithh i could not find, createDrawerNavigator.js in my node_modules folder... i would like to fix this issue asap sir

**Comment by ian-smithh** [comment]
@ayushagarwalk can you try [updating your @react-navigation/core](https://github.com/react-navigation/stack/issues/182#issuecomment-526562476) as was suggested

**Comment by ayushagarwalk** [comment]
@ian-smithh its latest version sir "@react-navigation/core": "^3.5.0"

**Comment by ian-smithh** [comment]
@ayushagarwalk maybe try reinstalling your node modules?

**Comment by jaikme** [comment]
Same here with "@react-navigation/core": "^3.5.0".

**Comment by sheixt** [comment]
@jaikme did you amend the node_module after going through that process?

I've run through the same steps you have and still get the following error on an Andriod simulator (running Pie): 
`(0. _reactNavigation.createAppContainer) is not a function. (In '(0, _reactNavigationStack.createAppContainer) (MealsNavigator)','(0, _reactNavigationStack.createAppContainer)' is undefined)`

**Comment by sheixt** [comment]
> I had this same issue, with either `react-navigation-stack@1.4.0` or `@1.5.0`. I was able to resolve it by making the following changes in createDrawerNavigator.js:
> 
> Line 3 from `import { ThemeColors, createNavigator } from '@react-navigation/core/';` to
> `import { ThemeColors, createNavigator } from '@react-navigation/core/src';`
> 
> ~I then added `const light = ThemeColors.light;` and changed the corresponding call later in the file to match this, I was doing this for troubleshooting and I don't think it is necessary, but YMMV. I also made the ThemeColors.ts in `@react-navigation/core/src` to a .js file, but again I don't think this is necessary. If anyone wants, I will test only changing the import.~
> EDIT: You do not need to do the steps that are crossed out, simply changing the import line is enough

@ian-smithh did you resolve the issue by making the change directly within the node_module or were you able to fix by reinstalling? I ask just I've completely wiped the `node_modules` directly and reinstalled them and the same issue persists.

Were we able to identify a stable version?

**Comment by jaikme** [comment]
> @jaikme did you amend the node_module after going through that process?
> 
> I've run through the same steps you have and still get the following error on an Andriod simulator (running Pie):
> `(0. _reactNavigation.createAppContainer) is not a function. (In '(0, _reactNavigationStack.createAppContainer) (MealsNavigator)','(0, _reactNavigationStack.createAppContainer)' is undefined)`


Yes, but I ended up having a lot of work to refactor to 4x version, so I chose not to use `"@react-navigation/core"` anymore. If I remember correctly, I ended up getting another error later with Themes, even directly changing node_modules to fix the error...
My current `package.json` looks like this, using ^3.11.0 ☹️ :

```json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll",
    "lint": "./node_modules/eslint/bin/eslint.js app",
    "lint:fix": "./node_modules/eslint/bin/eslint.js app --fix",
    "flow": "./node_modules/flow-bin/cli.js"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@ant-design/react-native": "^3.1.13",
    "@apollo/react-hooks": "^3.0.1",
    "@expo/samples": "~3.0.3",
    "@expo/vector-icons": "^10.0.3",
    "@react-navigation/web": "^1.0.0-alpha.9",
    "apollo-cache-inmemory": "^1.6.3",
    "apollo-client": "^2.6.4",
    "apollo-link": "^1.2.12",
    "apollo-link-error": "^1.1.11",
    "apollo-link-http": "^1.5.15",
    "expo": "^34.0.1",
    "expo-asset": "^6.0.0",
    "expo-barcode-scanner": "^6.0.0",
    "expo-camera": "^6.0.0",
    "expo-constants": "^6.0.0",
    "expo-font": "~6.0.0",
    "expo-localization": "^6.0.0",
    "expo-permissions": "^6.0.0",
    "expo-web-browser": "6.0.0",
    "graphql": "^14.4.2",
    "graphql-tag": "^2.10.1",
    "i18n-js": "^3.3.0",
    "intl": "^1.2.5",
    "prop-types": "^15.7.2",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-camera": "^3.3.3",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-reanimated": "^1.1.0",
    "react-native-safe-area-view": "^0.14.7",
    "react-native-svg": "^9.5.3",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "^0.11.4",
    "react-navigation": "^3.11.0",
    "react-navigation-header-buttons": "^3.0.2",
    "react-navigation-stack": "^1.4.0",
    "react-redux": "^7.1.0",
    "redux": "^4.0.4",
    "styled-components": "^4.3.2"
  },
  "devDependencies": {
    "@babel/cli": "^7.5.5",
    "@babel/core": "^7.5.5",
    "@babel/preset-flow": "^7.0.0",
    "babel-eslint": "^10.0.2",
    "babel-jest": "^24.8.0",
    "babel-plugin-import": "^1.12.0",
    "babel-plugin-module-resolver": "^3.2.0",
    "babel-preset-expo": "^6.0.0",
    "eslint": "^6.1.0",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-config-prettier": "^6.0.0",
    "eslint-import-resolver-babel-module": "^5.1.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.14.3",
    "eslint-plugin-react-hooks": "^1.7.0",
    "flow-bin": "^0.92.1",
    "husky": "^3.0.3",
    "jest": "^24.8.0",
    "jest-expo": "^34.0.0",
    "prettier": "^1.18.2",
    "react-test-renderer": "^16.9.0"
  }
}
```

**Comment by belal-mazlom** [comment]
This solution worked with me after a lot of trying and hours spend on that
Just want to mention you may need to clear cache when doing changes

```
watchman watch-del-all && react-native start --reset-cache
```

**Comment by ibra28x** [comment]
@sheixt thank u so match
