### ISSUE TITLE
[V2.0] Dismissing a modal is buggy on iOS13

### ISSUE THREAD

**Issue by iDuuck** [react-navigation/stack#187]
Don't have that much information about it, but just check out the Snack by @satya164 on an device that has iOS 13 installed: 

https://t.co/Tku9PSQkqe?amp=1

Dismissing the modal with a gesture is buggy for me.

**Comment by satya164** [comment]
What do you mean by "buggy"? Please provide more info

**Comment by jd20** [comment]
I don't know about iOS 13, but even on iOS 12, the modal doesn't always animate out when dismissing. It works very well when the gesture is done slowly, but when done too fast, it either doesn't animate, or will immediately dismiss as soon as you start to drag. I've attached a video showing the behavior.

![MFTL4942](https://user-images.githubusercontent.com/17896438/63646628-9068ee00-c6ca-11e9-8ebd-5021b9d25cc0.gif)

**Comment by satya164** [comment]
@osdnk do you have any ideas why this happens?

**Comment by osdnk** [comment]
Nothing of the top of my head. Sorry!

**Comment by gaodeng** [comment]
Similar problems exist on the android platform https://github.com/react-navigation/stack/issues/177
here is a video showing the bug.
https://www.youtube.com/watch?v=QJHNFIV3WzU

**Comment by satya164** [comment]
This should be fixed in latest alpha.

**Comment by mohmdalfaha** [comment]
Hi @satya164, thanks for implementing this. I am getting this error while trying to implement the new iOS 13 modal presentation you same way as you did:

`undefined is not an object (evaluating '_reactNavigationStack.TransitionPresets.ModalPresentationIOS')
`
Here's how I am trying to implement it 

`
//import { createAppContainer, createSwitchNavigator, } from '@react-navigation/native';
import { createAppContainer } from '@react-navigation/native';

import { createStackNavigator,TransitionPresets,} from 'react-navigation-stack';
import Menu from '@Pages/Menu';
import ProductDetails from '@Pages/ProductDetails';

const ModalStack = createStackNavigator(
    {ProductDetails},
    {Menu},
    {
      mode: 'modal',
      headerMode: 'none',
      initialRouteName: 'Menu',
      defaultNavigationOptions: {
        ...TransitionPresets.ModalPresentationIOS,
        gestureEnabled: true,
        cardOverlayEnabled: true,
      },
    }
  );
  

  const AppNavigator = createAppContainer(ModalStack);

export default AppNavigator
`

In your snack https://t.co/Tku9PSQkqe?amp=1 you are navigating within the same screen as a modal while I am trying to navigate to another screen. 

Any tips would be highly appreciated 

Thanks,

**Comment by mohmdalfaha** [comment]
Forget about the above error, the issue was that in my opinion is that there should be only one route in ModalStack which I figured out by myself, instead now I am getting this error when trying to use ```navigation.isFirstRouteInParent``` inside Menu screen 
```
TypeError: TypeError: is not a function. (In 'navigation.isFirstRouteInParent()', 'navigation.isFirstRouteInParent' is undefined)
```

I have used the same packages versions you used in the snack but not really getting this to work

**Comment by anastely** [comment]
Hey @mohmdalfaha Are u solve it ?

**Comment by mohmdalfaha** [comment]
@anastely I have solved just upgrade to the latest version.

**Comment by skantus** [comment]
This is working for me:

```
"react-navigation": "^4.0.10",
"react-navigation-stack": "^2.0.16",
"react-navigation-tabs": "^2.7.0",
"reactotron-react-native": "^3.6.4",

// Needed
"react-native-safe-area-context": "^0.6.2",
"@react-native-community/masked-view": "^0.1.6",
```

<img width="422" alt="Screenshot 2020-01-25 at 00 15 29" src="https://user-images.githubusercontent.com/4986411/73110741-d0e1c780-3f07-11ea-8f69-f35a7ab1e8af.png">

**Comment by anastely** [comment]
> This is working for me:
> 
> ```
> "react-navigation": "^4.0.10",
> "react-navigation-stack": "^2.0.16",
> "react-navigation-tabs": "^2.7.0",
> "reactotron-react-native": "^3.6.4",
> 
> // Needed
> "react-native-safe-area-context": "^0.6.2",
> "@react-native-community/masked-view": "^0.1.6",
> ```
> 
> <img alt="Screenshot 2020-01-25 at 00 15 29" width="422" src="https://user-images.githubusercontent.com/4986411/73110741-d0e1c780-3f07-11ea-8f69-f35a7ab1e8af.png">

Why we needed these packages?

**Comment by skantus** [comment]
@anastely to use `...TransitionPresets.ModalPresentationIOS`.

"@react-native-community/masked-view": "^0.1.6": 

https://reactnavigation.org/docs/en/stack-navigator.html

"@react-native-community/masked-view": "^0.1.6": 

https://reactnavigation.org/docs/en/next/handling-safe-area.html
