### ISSUE TITLE
Can not center title on android

### ISSUE THREAD

**Issue by thuann-vn** [react-navigation/stack#196]
It's seem setting headerLayoutPreset: 'center' not working
`const OrderStack = createStackNavigator(
OrderRoutes,{
  headerLayoutPreset: 'center',
  ...DEFAULT_NAVIGATION_OPTIONS
});`

**Comment by thuann-vn** [comment]
Any help here?

**Comment by sebinq** [comment]
I'm encountering same problem

**Comment by mistaker07** [comment]
@thuann-vn need more informations: the structure of DEFAULT_NAVIGATION_OPTIONS and OrderRoutes.

For me the basic setup below works: 
`const HomeStack = createStackNavigator({ Home: HomeScreen }, { headerLayoutPreset: 'center' })`

**Comment by sebinq** [comment]
For me 

```js
const getStackConfig = ({ initialRouteName }) => ({
  initialRouteName,
  headerLayoutPreset: "center"
});

const HomeStack = createStackNavigator(
  {
    Home: HomeScreen,
    Gallery: GalleryScreen
  },
  getStackConfig({ initialRouteName: "Home" })
);
```

and in screen: 

```js
HomeScreen.navigationOptions = ({ navigation }) => ({
  title: "Home",
});
```

doesn't work.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/stack-navigator-2.0.html#headertitlealign
