### ISSUE TITLE
Don't use `default` when you use web only type (boxShadow) in Platform.Select

### ISSUE THREAD

**Issue by adamgorMSFT** [react-navigation/stack#201]
Most places it doesn't matter that 'default' gets used when its really meant for web only, but in the places that 'boxShadow' is used, this is a web only field for StyleSheet.

So I am trying to get an app that works on android, ios, **windows**, and web.  
It works fine on 3 of the 4.(Doesn't work in windows because boxShadow). But I have to have a fork of the react-navigation/stack because `Platform.Select({ default:`  occasionally uses web only types. 

I know react native for windows is still fairly new and hasn't gained much momentum yet. I am not requesting to have a specific `windows:` case in the Platform.Select (unless you want too).  I am just asking to use `web:` for web only things, and default for the generic (all platform) fallback.  In this case its specifically only for boxShadow usage. 

Example:
https://github.com/react-navigation/stack/blob/6c251ccd3cf3e7b3bca7f60b08f69d634340b15e/src/views/Header/HeaderBackground.tsx#L25
In this scenario, here is my proposed change
* Can you use `web:` for boxShadow, and then have default be something more like the ios that uses generic things?
* Replace boxShadow in default for something that is generic and doesn't use web only types: `boxShadow`

However in places like this
https://github.com/react-navigation/stack/blob/master/src/views/Header/HeaderTitle.tsx
No change is needed.

**Comment by satya164** [comment]
pull request welcome

**Comment by pzatorski** [comment]
@satya164 I think Evan's solution works better in this case and he already created the PR for it but with the MR to react-navigation 1.0 branch
here: https://github.com/react-navigation/stack/pull/151/commits/04ce13f282ecd6d527395b1c27c4d619b61ab593

**Comment by namrog84** [comment]
That'll work perfectly!

**Comment by satya164** [comment]
Probably Evan doesn't have time to fix the conflicts and update the PR. So another PR is welcome.

**Comment by namrog84** [comment]
I'll look into this today. Should it be 1.0 master or which branch? Or all or them?

**Comment by satya164** [comment]
Both is good

**Comment by pzatorski** [comment]
I close this issue in favour of this: https://github.com/react-navigation/stack/pull/267
