### ISSUE TITLE
Allow passing custom `containerStyle` for StackItem or add ability to override default behaviour

### ISSUE THREAD

**Issue by Simek** [react-navigation/stack#209]
Currently due to implementation when user is using `headerTransparent: true` and custom header (`headerBackground`) it's not possible to retain top margin (safe area) under header element.

https://github.com/react-navigation/stack/blob/ee241aacd5dab42e27302df78f0cef8a43d99126/src/views/Stack/StackItem.tsx#L141-L145

It will be nice if we can pass `headerContainerStyle` object or alternatively `headerMode === 'float' && !headerTransparent && !hasCustomHeader` logic could be overridden by flag.

**Comment by Simek** [comment]
I would like to create PR for that. It will be nice if one of contributors selects or points the preferred way of fixing this issue.

**Comment by satya164** [comment]
What'd be the point of having a transparent header if you don't have content underneath?

**Comment by Simek** [comment]
At the beginning I want to admit that I'm using version `1.5.5` and I have use code snipppet from `master` which is `2.0.0-alpha.13`, my mistake.

Current V1 code looks like:
https://github.com/react-navigation/stack/blob/76d31321689391139a7a3b582d6c2898a659b313/src/views/StackView/StackViewLayout.tsx#L974-L980

So it makes more sense since you will have content under Header even when `{ paddingTop: floatingHeaderHeight }` is set, for example, when scrolling `FlatList` or `ScrollView` (espppecially combined with `react-native-community/react-native-blur` `BlurView` as header background). 

Currently without this fix initial position of `FlatList` (when using custom transparent header) is under header. Of course I can add some styling to each View/Card but I'm looking for global solution.

I have also tested `2.0.0-alpha.13`  but not much changed here in this particular case. Additionaly I have encountered following issues (iOS):
- I have to add  `react-native-community/masked-view` to my app dependencies and rebild (sice it's a peer dependency) otherwise Metro Bundler crashed on app launch
- when `undefined` is assigned to `headerLeft` or `headerRight` app crashes (`left/right` not a function) - passing dummy function `() => null` instead fixed that
- setting `headerBackTitle` to empty string or `null` do not affect label and "Back" titte appears with every back arrow

**Comment by Simek** [comment]
I have created simple Snack which should help understand the problem - https://snack.expo.io/@simek/42dcec - (unfortunately ATM V4 and `react-native-community/blur` not working on Expo).

I want archive following effect: initial position of `ScrollView` should be right beneath Header and when scrolling content it should overflow under Header and be still visible:

https://user-images.githubusercontent.com/719641/64758639-666e5300-d535-11e9-8ea1-918f3aad28ae.PNG

**Comment by Simek** [comment]
@satya164 ?

**Comment by satya164** [comment]
You'd need to add a top padding to the content in your scrollview manually. It's impossible for React Navigation to add a padding automatically afaik.

If you change that logic to always add the top padding in transparent header, the scrollview content will never go under the header, which is not desirable.
