### ISSUE TITLE
GestureHandler already initialized for root view

### ISSUE THREAD

**Issue by 90tad** [react-navigation/stack#212]
Sometime i got this error in my react-native project. I have no idea about where the problem come from.
I tried uninstall react-native-gesture-handler and re-install but it doesn't work

> expo version: ^34.0.1 
> react-native-gesture-handler: ^1.3.0

Platform : Android

[![My screenshot][1]][1]

  [1]: https://i.stack.imgur.com/7KHvT.jpg

**Comment by satya164** [comment]
Please open an issue in gesture handler repo with a screenshot that's readable.

**Comment by yosukapro** [comment]
Same issue here!

**Comment by DavidOmomia** [comment]
Please save a life,what is the fix to this issue,i have it too out of the blue on my project

**Comment by kwzm** [comment]
Same question!

**Comment by gaodeng** [comment]
the RNGH lib has caused too many problems, should we consider using the Gesture Responder System?
