### ISSUE TITLE
Issue with onDimensionChange and Header Height since RN v0.59.5

### ISSUE THREAD

**Issue by danjus10** [react-navigation/stack#217]
# Current Behavior

While using Navigation the Header height for Iphone X is rendered opposite as it should be when changing orientation (n.b. initial render is correct),  e.g. with top padding for landscape and slim for portrait.  

_Initial Render_
![image](https://user-images.githubusercontent.com/37114016/61699243-725a4780-ad32-11e9-9bc0-9dc09cf8dd03.png)
_Landscape_
![image](https://user-images.githubusercontent.com/37114016/61699271-856d1780-ad32-11e9-91ef-1b0aeee02e39.png)
_Portait_
![image](https://user-images.githubusercontent.com/37114016/61699301-9453ca00-ad32-11e9-9ada-ed9a089c34c6.png)

### Expected Behavior

In landscape the Header should be default header height.
In Portrait for Iphone X - It requires top padding to avoid notch area (... safe area).

Behaviour is consistent in RN v.59.4

### How to reproduce

- Install RN v.59.5-10

- Review RN commit - https://github.com/facebook/react-native/commit/72b4cc091d8451b80855c47e248fb693c78dc4a9
[iOS] [Fixed] - Pass back correct dimensions for application window in Dimensions module

You can see the window and screen dimensions logic returned from native have been changed.  It seems to return the window the same regardless of orientation.

![image](https://user-images.githubusercontent.com/37114016/61698747-85204c80-ad31-11e9-903f-254c78786d95.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^2.18.3 (also tried with v3.x)
| react-native     | .59.5

FYI - I've cross posted a link to this in the commit discussion.  https://github.com/facebook/react-native/pull/19932#issuecomment-514127313

**Comment by Rapsssito** [comment]
Having same issue.

**Comment by danjus10** [comment]
I am using RN 59.4 till I get time to resolve properly

—
Get fluid.work and work a better day.
________________________________
