### ISSUE TITLE
HeaderBackButton props

### ISSUE THREAD

**Issue by Baterka** [react-navigation/stack#234]
I need to use `HeaderBackButton` component imported from `react-navigation-stack` and I can't find documentation for this component's props.
Required props I don't know what to fill: `layoutPreset, scene`

**Comment by PierreCapo** [comment]
@Baterka are you using flow in your project ? It seems that the flow type definition is wrong for this component

[From flow-typed:](https://github.com/flow-typed/flow-typed/blob/536c49233246dc8649890dd9593e7fa2cde65284/definitions/npm/react-navigation-stack_v1.x.x/flow_v0.104.x-/react-navigation-stack_v1.x.x.js#L609)

```Javascript
  declare type _HeaderBackButtonProps = {|
    disabled?: boolean,
    onPress: () => void,
    pressColorAndroid?: string,
    tintColor?: ?string,
    backImage?: React$ComponentType<{
      tintColor: string,
      title?: ?string,
      ...
    }>,
    title?: ?string,
    truncatedTitle?: ?string,
    backTitleVisible?: boolean,
    allowFontScaling?: boolean,
    titleStyle?: ?TextStyleProp,
    headerLayoutPreset: 'left' | 'center',
    width?: ?number,
    scene: NavigationStackScene,
  |};
```

[From react-navigation-stack](https://github.com/react-navigation/stack/blob/64c14bb20a8cf1b0c060f3ee338528346bb59625/src/types.tsx#L161)

```TypeScript
export type HeaderBackButtonProps = {
  disabled?: boolean;
  onPress?: () => void;
  pressColorAndroid?: string;
  backImage?: (props: { tintColor: string }) => React.ReactNode;
  tintColor?: string;
  label?: string;
  truncatedLabel?: string;
  labelVisible?: boolean;
  labelStyle?: React.ComponentProps<typeof Animated.Text>['style'];
  allowFontScaling?: boolean;
  onLabelLayout?: (e: LayoutChangeEvent) => void;
  screenLayout?: Layout;
  titleLayout?: Layout;
  canGoBack?: boolean;
};
```

It seems they are quite different and I suspect it is what is causing your issue. I gonna open an issue on flow-typed for that

**Comment by satya164** [comment]
> Required props I don't know what to fill: layoutPreset, scene

These props are passed by react navigation when using a custom back button. You're not supposed to pass them yourself.

Regarding documentation, PRs welcome.
