### ISSUE TITLE
gestureEnabled: false doesn't work on iOS on React Native 0.61

### ISSUE THREAD

**Issue by dimitarnestorov** [react-navigation/stack#236]
And the following warning shows up when you start to drag
![image](https://user-images.githubusercontent.com/8790386/65552781-f6e16600-df2d-11e9-82de-80addbac2353.png)

**Comment by osdnk** [comment]
It will be working with the new release of RNGH

**Comment by satya164** [comment]
I believe it's fixed in https://github.com/facebook/react-native/commit/9f0dede1c913612e1241432f4cbccdc74d23a1e4 and released in a patch release: react-native 0.61.1

**Comment by dimitarnestorov** [comment]
It wasn't fixed in 0.61.1

**Comment by satya164** [comment]
Can you provide a GitHub repo with runnable demo to debug it?

**Comment by dimitarnestorov** [comment]
While making the demo I placed it somewhere else and it worked.
