### ISSUE TITLE
tabBarVisible: false on react-navigation-stack

### ISSUE THREAD

**Issue by Ahmad31** [react-navigation/stack#240]
I used the tabBarVisible: false  on the react-navigation-stack, but it doesn't work

``` import { createAppContainer } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';

const MainStack = createStackNavigator({
    HomeScreen: {
        screen: HomeScreen,
        navigationOptions: () => ({
            header: null
        }),
    },
    MakeupArea: {
        screen: MakeupArea,
        navigationOptions: ({ navigation }) => ({
            tabBarVisible: false
        })
    },
    SceenBarcodeFN: {
        screen: SceenBarcodeFN,
        navigationOptions: ({ navigation }) => ({
            header: null,
            tabBarVisible: false
        })
    }
}, {
    initialRouteName: 'HomeScreen'
})
MainStack.navigationOptions = ({ navigation }) => {
    if (navigation.state.index == 0) {
        return {
            tabBarVisible: true
        };
    }
    return {
        tabBarVisible: false
    };
};
export default createAppContainer(MainStack); 
```

**Comment by Grohden** [comment]
@Ahmad31 there is no `tabBarVisible` on navigation stack: 
https://reactnavigation.org/docs/en/stack-navigator.html

Are you trying to hide the tab bar from a bottom navigation? https://reactnavigation.org/docs/en/bottom-tab-navigator.html#tabbarvisible

I suggest you to use:
```
 stack -> 
   bottomNavigator: 
      -> bottomRouteOne
      -> bottomRouteTwo
   routeThatDontHaveBottomOne
   routeThatDontHaveBottomTwo
```
That way the stack will open those routes above the bottom tab and 'hide' it.

But if you need to hide the bottom tab bar anyway you will need to configure on the tab `navigationOptions` definition not on the stack.

btw: I'm not a maintainer :P I just happen to have time to **try** to help.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/navigation-options-resolution.html

**Comment by Atomo87** [comment]
const AppNavigator = createBottomTabNavigator({

 HomeScreen: {
      screen:  HomeScreen
  },
MakeupArea: {
screen: MakeupArea

  },
  SceenBarcodeFN: {
    screen:  SceenBarcodeFN
    
      }


},
{
 defaultNavigationOptions: {
     header: null

 }


})
