### ISSUE TITLE
Unable to resolve module './views/Header/HeaderStyleInterpolator

### ISSUE THREAD

**Issue by MorgadoKnivet** [react-navigation/stack#260]
Hello People. I did update react-navigation-stack to  "react-navigation-stack": "^2.0.0-alpha.26" to implement ios 13 modal. Can help me with issue? Thanks.

![Screen Shot 2019-10-13 at 12 05 01](https://user-images.githubusercontent.com/34779500/66717650-b305b200-edb1-11e9-99de-236027d64165.png)

React-Native - 60.5
React-navigation-stack - 2.0.0-alpha.26

**Comment by satya164** [comment]
try deleting your `node_modules` and reinstalling, and/or `react-native start --reset-cache` (`expo start -c` if using expo).

**Comment by MorgadoKnivet** [comment]
Thanks @satya164 . Perfect.
