### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by DimaShcherbakov** [react-navigation/stack#263]
app crashed when I'm importing createStackNavigator with error 'Native module cannot be null'
rn: 0.59.2
react: 16.9
react-navigation: 4
react-navigation-stack: 2.0.0.- alfa.27

**Comment by satya164** [comment]
Please install and link all the required deps as mentioned in the docs https://reactnavigation.org/docs/en/stack-navigator-2.0.html

If you're facing an issue, open a bug report with a proper stack trace and a reproducible demo.

**Comment by DimaShcherbakov** [comment]
Can it be possible to use it in versions what were installed below
"@react-native-community/masked-view": "^0.1.1",
        "@react-navigation/core": "^3.5.1",
        "@react-navigation/stack": "^5.0.0-alpha.20",
        "@types/date-fns": "^2.6.0",
        "@types/numeral": "0.0.25",
        "@types/react-native-fbsdk": "^0.6.3",
        "@types/react-native-permissions": "^1.1.1",
        "@types/react-native-tab-view": "^1.0.6",
        "axios": "^0.18.0",
        "currency-symbol-map": "^4.0.4",
        "date-fns": "^1.30.1",
        "hoist-non-react-statics": "^3.3.0",
        "i18next": "^17.0.6",
        "lodash": "^4.17.15",
        "moment": "^2.24.0",
        "numeral": "^2.0.6",
        "ramda": "^0.26.1",
        "react": "^16.9.0",
        "react-art": "^16.8.6",
        "react-dom": "^16.8.6",
        "react-i18next": "^10.11.4",
        "react-native": "0.59.2",
        "react-native-camera": "^2.10.2",
        "react-native-contacts": "^4.0.2",
        "react-native-device-info": "^2.1.2",
        "react-native-drag-drop-and-swap": "^0.1.6",
        "react-native-dropdownalert": "^3.11.0",
        "react-native-elements": "^1.1.0",
        "react-native-fbsdk": "git://github.com/facebook/react-native-fbsdk.git#4fe3dbbb4e2bd955d2cd447d94264d80ffd0eaea",
        "react-native-firebase": "^5.4.2",
        "react-native-gesture-handler": "^1.1.0",
        "react-native-google-places": "^3.0.5",
        "react-native-keyboard-aware-scroll-view": "^0.9.1",
        "react-native-linear-gradient": "^2.5.4",
        "react-native-localize": "^1.1.0",
        "react-native-modal": "^11.3.1",
        "react-native-modal-overlay": "^1.3.1",
        "react-native-modal-picker": "0.0.16",
        "react-native-modal-selector": "^1.0.3",
        "react-native-notification-android-permission-library": "^1.0.8",
        "react-native-permissions": "^1.1.1",
        "react-native-picker-select": "^6.1.0",
        "react-native-qrcode-scanner": "^1.1.0",
        "react-native-qrcode-svg": "^5.1.2",
        "react-native-raw-bottom-sheet": "^2.0.2",
        "react-native-reanimated": "^1.0.1",
        "react-native-safe-area-context": "^0.5.0",
        "react-native-screens": "^2.0.0-alpha.4",
        "react-native-share": "^1.2.1",
        "react-native-splash-screen": "^3.2.0",
        "react-native-svg": "^9.3.6",
        "react-native-tab-view": "^2.2.0",
        "react-native-touch-id": "^4.4.1",
        "react-native-user-defaults": "^0.1.5",
        "react-native-vector-icons": "^6.4.2",
        "react-native-webview": "^5.12.1",
        "react-navigation": "^4.0.10",
        "react-navigation-drawer": "^2.2.2",
        "react-navigation-redux-helpers": "^3.0.0",
        "react-navigation-stack": "^2.0.0-alpha.27",
        "react-navigation-tabs": "^2.5.6",
        "react-redux": "^6.0.1",
        "redux": "^4.0.1",
        "redux-form": "^8.1.0",
        "redux-persist": "^5.10.0",
        "redux-saga": "^1.0.2",
        "redux-thunk": "^2.3.0",
        "reselect": "^4.0.0",
        "validate.js": "^0.12.0"

**Comment by satya164** [comment]
The error message means that you haven't linked something. Version probably doesn't matter.

Also you need 1.x of screens, you have 2.x installed.
