### ISSUE TITLE
createStackNavigator returns any object in type definitions

### ISSUE THREAD

**Issue by keshavkaul** [react-navigation/stack#276]
I'm unable to correctly find the type of the returned stack navigator component.

From Type Declaration File of createStackNavigator
```
declare function createStackNavigator(routeConfigMap: NavigationRouteConfigMap<NavigationStackOptions, NavigationStackProp<NavigationRoute, any>>, stackConfig?: CreateNavigatorConfig<NavigationStackConfig, NavigationStackRouterConfig, NavigationStackOptions, NavigationStackProp<NavigationRoute, any>>): any;
```

Issue in In version 1.10.3

**Comment by satya164** [comment]
Can you give some more details please?

**Comment by keshavkaul** [comment]
@satya164 
Generated typescript type declaration file present in location:
`lib/typescript/navigators/createStackNavigator.d.ts` has return type of the method as **any**

**Comment by satya164** [comment]
TS definitions should work fine now.
