### ISSUE TITLE
Custom header does not work if configured in RouteConfig

### ISSUE THREAD

**Issue by manishjanky** [react-navigation/stack#279]
For the stack navigation if you want to have a custom header and specify the same in the RouteConfig the same does not work instead just displays a white empty header even when the headerMode is set to float or screen doesn't matter. For example 
```
 const MyScreen1Stack = createStackNavigator(
    {
       Screen1: {
          screen: Screen1,
       }
    },
    {
       heaMode: 'screen' , // or even float
       navigationOptions: ({ navigation }) => ({
          initialRouteName: 'Screen1',
          title: 'Screen 1',
          drawerLabel: 'Screen 1',
          header: ()=> <MyHeader />
       }),
    },
 );
```

Where `MyHeader` is a simple react component 
` <View><Text>My Custom Title</Text></View>`

Even if you do this in `defaultNavigationOptions `i get the same result.
Whereas the [documentation ](https://reactnavigation.org/docs/en/stack-navigator.html#header) says that

> React Element or a function that given HeaderProps returns a React Element, to display as a header.

Version Info:
```
   "react-navigation": "^4.0.10",
    "react-navigation-drawer": "^2.3.1",
    "react-navigation-stack": "^1.10.2",
    "react-navigation-tabs": "^2.5.6"
```

Not sure if this is a bug or not. But i would really like to configure my header with the route config.

**Comment by satya164** [comment]
Works fine https://snack.expo.io/SJgRgZ_cB

**Comment by manishjanky** [comment]
@satya164 Could it be because my stack is i created to show headers for the drawer which is nested inside a tab navigator. Because this is a issue i'm facing and even tried changing versions and did not work.

**Comment by manishjanky** [comment]
Also here is a demo of that is would not work if specified with `navigationOptions` and not `defaultNavigationOptions`. But the docs say this will work if part of `navigationOptions` as well.

[try this out](https://snack.expo.io/rydtO-Oqr)

**Comment by satya164** [comment]
They are not the same https://reactnavigation.org/docs/en/navigation-options-resolution.html
