### ISSUE TITLE
Title bar jumping on all versions that use react native safe view context

### ISSUE THREAD

**Issue by harisb2012** [react-navigation/stack#283]
Hey guys,

This is happening to me since I upgraded app to use version with safe context area. (alpha 20+).

What might be causing this?

![giffff](https://user-images.githubusercontent.com/4821356/68380699-a1b18a80-0150-11ea-8723-9829722b9b82.gif)

**Comment by sallar** [comment]
Im experiencing this as well.

**Comment by satya164** [comment]
Can you provide a repro please?

**Comment by dmitov** [comment]
This happens if `headerMode` is set to `none`.

**Comment by harisb2012** [comment]
I found it to be really buggy with react native safe area context. Alphas 21 + are totally unstable for me. Had few issues on android as well.

**Comment by zackify** [comment]
I found this happening as well,  only when i try to make a nested stack nav:

```
const AuthenticationRoutes = createStackNavigator(
  {
    Home: {
      screen: TestHome,
      navigationOptions: {
        title: 'Home',
      },
    },
    Login: {
      screen: Login,
      navigationOptions: {
        title: 'Login',
        //...TransitionPresets.SlideFromRightIOS,
      },
    },
    RegisterRoutes: {
      screen: createStackNavigator(
        {
          Register: {
            screen: Register,
            navigationOptions: {
              title: 'Create Account',
            },
          },
        },
        {
          headerMode: 'none',
        },
      ),
    },
  },
  {
    mode: 'modal',
    headerMode: 'none',
    defaultNavigationOptions: {
      gestureEnabled: true,
      cardOverlayEnabled: true,
      headerStyle: {
        backgroundColor: '#000000',
      },
      headerTintColor: '#fff',
      headerTitleStyle: {
        fontWeight: 'bold',
      },
      ...TransitionPresets.ModalPresentationIOS,
    },
  },
);```

The goal here was: open register as a modal, register has screens inside it that should do normal transitions inside of the modal

**Comment by satya164** [comment]
@janicduplessis is looking into it

**Comment by satya164** [comment]
Can someone check if this workaround prevents jump for you? https://github.com/react-navigation/stack/compare/@satya164/safe-area-compar

**Comment by zackify** [comment]
@satya164 yess! that works perfectly. 

P.S. now i know how to develop on this repo. had to add those changes, then pull out the package from my node modules, and yarn bootstrap. i should have just cloned this first :P 

Any idea when this can get in?

**Comment by satya164** [comment]
I'll do a release with it tonight

**Comment by satya164** [comment]
https://github.com/react-navigation/stack/releases/tag/v2.0.0-alpha.37

**Comment by zackify** [comment]
You’re the best! Appreciate the quick release
