### ISSUE TITLE
APP CRASH: Invariant Violation: Unsupported top level event type "onGestureHandlerStateChange" dispatched

### ISSUE THREAD

**Issue by JeremyBradshaw7** [react-navigation/stack#286]
Getting this error on migrating to the latest v4 react-navigation packages and importing creatStackNavigator from react-navigation-stack. It's happening simply when hitting the back button from a specific screen to go back to the root screen of the stack (or trying a swipe gesture to go back). But it's only happening on a device (iOS) in a production build, not a simulator or even a device on a dev build, which makes testing workarounds extremely time-consuming. I'm picking up the error in a Sentry crash report, the app just crashes.

Versions of packages below:
```
		"react-navigation": "^4.0.10",
		"react-navigation-drawer": "^2.3.3",
		"react-navigation-slide-from-right-transition": "^1.0.4",
		"react-navigation-stack": "^1.10.3",
		"react-navigation-tabs": "^2.5.6",
```

Creation of Stack Navigator:
```
export const SettingsStack = createStackNavigator({
  Settings: {
    screen: Settings,
    navigationOptions: {
      header: null
    }
  },
  About: {
    screen: About,
    navigationOptions: {
      header: null
    }
  },
  ChangePassword: {
    screen: ChangePassword,
    navigationOptions: {
      header: null
    }
  },
  ResponsibilitiesConfig: { screen: ResponsibilitiesConfig }
}, {
    headerMode: 'float',
    headerTransitionPreset: 'uikit',
    defaultNavigationOptions: {
      headerBackTitle: null,
      headerBackImage: ({tintColor, title}) => <Icon style={{ marginLeft: 8, color: tintColor }} type='Ionicons' name='md-arrow-back' />,
      gesturesEnabled: true // can swipe back
    },
    transitionConfig: getSlideFromRightTransition
  });
```

Error is happening on going back from ResponsibilitiesConfig to Settings. ResponsibilitiesConfig has header configuration as follows, not overriding the default headerLeft :

```
  // Header configuration
  static navigationOptions = ({ navigation }) => {
    // const params = navigation.state.params || {};
    return {
      headerStyle: { borderBottomWidth: 1, marginTop: Platform.OS === 'android' ? 20 : 0 }, // fix for half obscured header on android
      headerBackground: <Wallpaper header />,
      headerTintColor: WallpaperSecondaryColor,
      headerTitleStyle: { flex: 1, textAlign: 'center', color: WallpaperPrimaryColor },
      headerTitle: <HeaderTitle overWallpaper title={$labels.RESPONSIBILITIES.CONFIG_TITLE} />,
      headerRight: <HelpMenu />
    };
  }
```

**Comment by JeremyBradshaw7** [comment]
Note: doesn't seem to make any difference if I set `gesturesEnabled: false` in the stack navigator config.

**Comment by JeremyBradshaw7** [comment]
I'm now getting this error thrown every time I select an option from a DrawerNavigator menu, so will raise in the main repo.

**Comment by zackify** [comment]
In debug mode, my simulator lags a lot with a modal coming up. When I switch to a production build, as the modal slides up the app crashes with this problem

**Comment by satya164** [comment]
@zackify have you added `import 'react-native-gesture-handler'` to the top of your entry file?

this is a known issue with gesture handler https://github.com/kmagiera/react-native-gesture-handler/issues/320

**Comment by JeremyBradshaw7** [comment]
What worked for me in the end was to put this import as the first line in the root index file AND in any file that calls react-navigation's createAppContainer method :

import 'react-native-gesture-handler';

And then this immediately after all the imports in your root index file:

// fix for https://github.com/kmagiera/react-native-gesture-handler/issues/320
if (Platform.OS === 'android') {
  const { UIManager } = NativeModules;
  if (UIManager) {
    // Add gesture specific events to genericDirectEventTypes object exported from UIManager native module.
    // Once new event types are registered with react it is possible to dispatch these events to all kind of native views.
    UIManager.genericDirectEventTypes = {
      ...UIManager.genericDirectEventTypes,
      onGestureHandlerEvent: { registrationName: 'onGestureHandlerEvent' },
      onGestureHandlerStateChange: {
        registrationName: 'onGestureHandlerStateChange',
      },
    };
  }
}

It would still be better to have it properly fixed in the repo so that these workarounds aren't necessary, so I don't think this should have been closed.
