### ISSUE TITLE
 Header section is flickering while navigating from a stack navigator to headerRightNavigation

### ISSUE THREAD

**Issue by nihp** [react-navigation/stack#287]
I am using react-navigation to navigate the screens. Here I have used TabBarBotoom and stack navigator.

The headerRight (header right there is 3 icons) is inside the stacknavigator so while navigating it gets flickering. Any solution for this. In header right there?

```
renderMyHomeHeader = (navigation) => {
  let navigationOptions = {
    headerStyle: {
      backgroundColor: 'black',
      borderWidth: 0,
      borderBottomWidth: 0,
      width: deviceWidth,
      height:  headerHeight
    },
    headerLeft: headerTitleNavigationOptions('Home'),
    //headerLeft: headerLeftNavigatorOptions(navigation),
    headerRight: headerRightNavigatorOptions(navigation) // Here I have many screens
  };

  navigationOptions: ({ navigation }) => ({
  headerStyle: {
      backgroundColor: 'black',
      borderWidth:0,
      borderBottomWidth:0
  },
})

  if (navigation.state.routeName != 'Home') {
    navigationOptions = {
      header: null
    };
  }
  return navigationOptions;
}

const BottomTabNavigator = createBottomTabNavigator({
  Home: {
    screen: createStackNavigator({
     HomeScreen: {
        screen: HomeScreen
      },
      User: {
        screen: User
      },
    },
    {
      defaultNavigationOptions: ({ navigation }) => (
        renderMyHomeHeader(navigation)
      ),
      navigationOptions: ({ navigation }) => ({
        tabBarVisible: showTabBar(navigation),
        tabBarIcon: ({focused}) =>  (<Image style={{tintColor: focused ? '#C7A985': '#FFFFFF', width: 45, borderColor:'white', height:45, paddingTop:0, resizeMode:'contain'}} source={{uri: 'image'}} />),
        //tabBarIconColor: 'white',
        tabBarOnPress: ({}) => (navigation.navigate('Home')),
        inactiveTintColor:'white'
      }),
      transitionConfig: () => ({
          transitionSpec: {
            duration: 0,
            timing: Animated.timing,
            opacity: 0
          },
        }),
      },
    ),
  },

```
Version:

**"react-navigation": "^3.2.3"**
**"react": "16.8.1",**
**react-native-cli: 2.0.1**
**react-native: 0.58.4**

**Comment by nihp** [comment]
@brentvatne Can you able to look into this issue and kindly add your suggestion about this

**Comment by satya164** [comment]
Can you share a GIF showing what the flicker looks like? Regardless, you might want to upgrade to 2.0 https://reactnavigation.org/docs/en/stack-navigator-2.0.html

**Comment by nihp** [comment]
@satya164  I am using react-navigation version 3.

Did you mean while upgrading react-navigation I need to upgrade the createStackNavigator also? Can you elaborate?

Because I Just import createStackNavigator from the react-navigation.

How can I check the version of createStackNavigator?

**Comment by nihp** [comment]
@satya164 While navigating it shows a white color blinking (i.e) a white flash in the screen.

**Comment by pzatorski** [comment]
@nihp To use `createStackNavigator` you should upgrade to react-navigation v4. Here is [the guide](https://reactnavigation.org/blog/2019/09/16/react-navigation-4.0.html). As far as I remember react-navigation v3 doesn't use `createStackNavigator`. If you don't want to upgrade to react-navigation v4 for some reason you should follow [this guide](https://reactnavigation.org/docs/en/3.x/getting-started.html) while using react-navigation v3.
If you still having "blinking" issue please include GIF for it as **satya164** mentioned above.

**Comment by nihp** [comment]
I am using react-navigation **react-navigation@3.12.1** . Are you saying react-navigation version 3 don't use `createStackNavigator`?  But in the[ version 3 documentation](https://reactnavigation.org/blog/2018/11/17/react-navigation-3.0.html) have createStackNavigator. I think you suggestion is wrong. Kindly confirm once again.

Kindly look into version 3 documentation too. It using `createStackNavigator`. 

@satya164 

I have a clarification did the `**{cardStyle: opacity: 1}**` will helps here to solve this issue.

For the GIF kindly refer the gif from this comment. This is the [issue what I am experience ](https://github.com/react-navigation/react-navigation/issues/5767#issue-428719824)while navigate from the BottomTabBar (createStackNavigator) to Header right icon.

**Comment by pzatorski** [comment]
@nihp yes, sorry that I didn't specify more what I meant by using `createStackNavigator` from different versions of react-navigation.
If you are using the `createStackNavigator` from v3 you are importing it from 'react-navigation'. But from v4 there is separate packages for it: `react-navigation-stack` from where you import `createStackNavigator`.  And to be honest with you I'm not sure if using react-navigation v3 will have correct behaviour with using `createStackNavigator` from `react-navigation-stack`. So that's why I suggested you to upgrade to v4 and follow the guideline.

**Comment by nihp** [comment]
Okay no problem @pzatorski 

I think it has any solution in v3 itself. I need to found a solution temporary and then I need to upgrade to v4.

**Comment by pzatorski** [comment]
Great! If this issue still appears after you upgrade to the latest, please open new issue with runnable repo so we can have a look and in case of any bugs fix it. Thanks a lot!

**Comment by nihp** [comment]
Kindly reopen this ticket. Will close this after fixing this
