### ISSUE TITLE
Title does not truncate

### ISSUE THREAD

**Issue by miguelneves** [react-navigation/stack#290]
The long titles should truncate and fill a single line. It works on the previous version of react navigation stack

![Screenshot 2019-11-14 at 12 12 36](https://user-images.githubusercontent.com/736753/68856423-5d863300-06d8-11ea-91a5-fd75d77d8334.png)

"react-native": "0.61.4"
"react-navigation": "^4.0.10"
"react-navigation-stack": "^2.0.0-alpha.37"

**Comment by pzatorski** [comment]
Hey @miguelneves from the included image I guess that this is happening when headerBackTitle doesn't fit on the screen. So you should try to include something like this in the navigationOptions of this screen:
```
Home: {
    screen: HomeScreen,
    navigationOptions: () => ({
      title: `Home`,
      headerBackTitle: 'A much too long text for back button from RandomScreen to Home',
      headerTruncatedBackTitle: `to Home`,
    }),
  },
```
Let me know if this helps.

**Comment by miguelneves** [comment]
Your example works because the title is short. In my case, the title of parent screen is actually null, it's the title of the current screen that is too long.
It looks like the width of the title component is not being set.

**Comment by pzatorski** [comment]
It doesn't matter if parent screen is null. It will be nice if you could provide runnable repo. You can use [expo snack](https://snack.expo.io/). I try to reproduce the same behaviour in my app and for me all is working..
In my "Screen" Component:
```
static navigationOptions = ({ navigation }) => ({
    title: "This is really long Current Screen Title",
  });
```
Screen in the app:
![IMG_0299](https://user-images.githubusercontent.com/11720377/68940058-76f3b180-07a2-11ea-9dd5-285463e517fb.PNG)

**Comment by miguelneves** [comment]
Here is the snack example: https://snack.expo.io/@jorge.ribeiro.fhp/36b053

**Comment by pzatorski** [comment]
Thanks @miguelneves for reporting the issue. I will link this issue to the upcoming PR with fix for it.
