### ISSUE TITLE
v2.0.0 vs. v2.0.0-alpha

### ISSUE THREAD

**Issue by kellycampbell** [react-navigation/stack#292]
Did you guys mean to leave a v2.0.0 version published on npm? I don't see a tag for it in git and also there's been several more alphas since.

https://www.npmjs.com/package/react-navigation-stack/v/2.0.0

**Comment by satya164** [comment]
It was not intentional. You should use the alpha.

**Comment by kellycampbell** [comment]
You may want to `npm unpublish` the `2.0.0` version so people don't pick it up by accident.

**Comment by satya164** [comment]
It's not possible to unpublish modules

**Comment by kellycampbell** [comment]
It's possible, but I see now that it has to be done within 72 hours of the publish or you have to contact support.

https://docs.npmjs.com/unpublishing-packages-from-the-registry
