### ISSUE TITLE
Header Title component can't have hooks

### ISSUE THREAD

**Issue by sidferreira** [react-navigation/stack#295]
I use a custom component that changes some styles based on app's theme.

The code is basically:
```
export const HeaderTitle = ({ style = null, ...remainingProps }) => {
  const { appTheme } = useUserSettings();
  const isLightMode = appTheme === 'light';
  const headerTitleStyle = isLightMode
    ? fonts.style.body1Light
    : fonts.style.body1;

  return (
    <OriginalHeaderTitle
      {...remainingProps}
      style={[...style, headerTitleStyle]}
    />
  );
};
```

And I receive an `Invariant Violation` saying I'm breaking the Ryles of Hooks.

Weird is that if I add a try-catch around it the component works properly.

We're using React Native 0.61.4 and the latest React Navigation libraries

**Comment by satya164** [comment]
You haven't shared any code of how you use it, but I'm assuming you're doing `headerTitle: CustomHeaderTitle`. As per the docs, it's a function that returns an element, not a component. You need to do `headerTitle: props => <CustomHeaderTitle {...props} />`

**Comment by sidferreira** [comment]
Hey @satya164! 
Thanks for the info!
In this case, I think the docs must be updated: 

https://reactnavigation.org/docs/en/stack-navigator.html#headertitle

We've been using this with 3.2.1 so it was a surprise it stops working...
