### ISSUE TITLE
Wrong modal header height

### ISSUE THREAD

**Issue by rafaelmotta** [react-navigation/stack#301]
Just started a project from scratch in order to test, and I'm facing this issue with the navigation header height:

![Simulator Screen Shot - iPhone 11 - 2019-11-30 at 09 53 18](https://user-images.githubusercontent.com/446731/69898271-683afc00-1357-11ea-8e6e-97f99abcd6f7.png)

My dependencies:

```
"dependencies": {
    "@react-native-community/masked-view": "^0.1.5",
    "@react-navigation/core": "^5.0.0-alpha.25",
    "@react-navigation/native": "^5.0.0-alpha.16",
    "@react-navigation/stack": "^5.0.0-alpha.38",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-reanimated": "^1.4.0",
    "react-native-safe-area-context": "^0.6.1",
    "react-native-screens": "^2.0.0-alpha.15"
  }
```

Code:

```
import * as React from 'react';
import {Button, View, Text} from 'react-native';
import {NavigationNativeContainer} from '@react-navigation/native';
import {createStackNavigator, TransitionPresets} from '@react-navigation/stack';

function HomeScreen({navigation}) {
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <Text style={{fontSize: 30}}>This is the home screen!</Text>
      <Button
        onPress={() => navigation.navigate('MyModal')}
        title="Open Modal"
      />
    </View>
  );
}

function DetailsScreen() {
  return (
    <View>
      <Text>Details</Text>
    </View>
  );
}

function ModalScreen({navigation}) {
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <Text style={{fontSize: 30}}>This is a modal!</Text>
      <Button onPress={() => navigation.goBack()} title="Dismiss" />
    </View>
  );
}

const MainStack = createStackNavigator();
const RootStack = createStackNavigator();

function MainStackScreen() {
  return (
    <MainStack.Navigator>
      <MainStack.Screen name="Home" component={HomeScreen} />
      <MainStack.Screen name="Details" component={DetailsScreen} />
    </MainStack.Navigator>
  );
}

const Stack = createStackNavigator();

function App() {
  return (
    <NavigationNativeContainer>
      <RootStack.Navigator mode="modal">
        <RootStack.Screen
          name="Main"
          component={MainStackScreen}
          options={{headerShown: false}}
        />
        <RootStack.Screen
          name="MyModal"
          component={ModalScreen}
          options={{
            gestureEnabled: true,
            cardOverlayEnabled: true,
            ...TransitionPresets.ModalPresentationIOS,
          }}
        />
      </RootStack.Navigator>
    </NavigationNativeContainer>
  );
}

export default App;
```

**Comment by rgoldiez** [comment]
@rafaelmotta this isn't documented as far as I can tell, but it looks like you need to add additional config to your modal stack options to get rid of the extra space up top.  You might also need to explicitly set the height of in `headerStyle`
```
safeAreaInsets: { top: 0 },
headerStyle: {
  height: ??
}
```

**Comment by timjuenemann** [comment]
@rgoldiez I tried your solution, but `safeAreaInsets` doesn't work.

**Comment by rgoldiez** [comment]
@timjuenemann did you set the `headStyle.height`?

**Comment by timjuenemann** [comment]
@rgoldiez yes I did but I did something wrong elsewhere, sorry. 

By setting `safeAreaInsets: { top: 0 }` another bug is introduced:
![Simulator Screen Shot - iPhone 11 Pro - 2019-12-14 at 00 02 40](https://user-images.githubusercontent.com/14848797/70837721-391b9480-1e05-11ea-951c-03523049f59a.png)

**Comment by mefjuu** [comment]
The same problem here. I'm using TransitionPresets.ModalPresentationIOS.
Without `safeAreaInsets: { top: 0 }` it is:
![image](https://user-images.githubusercontent.com/2331923/70917053-f3391900-201c-11ea-8062-42d0f9c4a922.png)

With `safeAreaInsets: { top: 0 }`:
![image](https://user-images.githubusercontent.com/2331923/70917095-01873500-201d-11ea-8f5a-193a39312adc.png)

So the parameter affects header properly, but also it looks like it shifted the whole screen's container undesirably up. Maybe it's worth considering separation of safeAreaInsets behaviour in case of ModalPresentationIOS usage?

**Comment by satya164** [comment]
As of the latest version, you can use `headerStatusBarHeight: 0`

**Comment by jvandenaardweg** [comment]
Does not seem to work

```
"react-navigation": "^4.1.0",
 "react-navigation-stack": "^2.0.16",
```

```typescript
const OnboardingStack = createStackNavigator(
  {
    Onboarding: OnboardingScreen,
    Login: LoginStack,
    Signup: SignupStack
  },
  {
    initialRouteName: 'Onboarding',
    mode: 'modal',
    headerMode: 'screen',
    defaultNavigationOptions: ({ screenProps }: { screenProps: any }) => ({
      ...stackNavigatorDefaultNavigationOptions(screenProps.theme),
      headerShown: false,
      ...(Platform.OS === 'ios') ? TransitionPresets.ModalPresentationIOS : TransitionPresets.ModalTransition,
      headerStatusBarHeight: 0,
    })
  }
)
```

<img width="456" alt="Screenshot 2020-01-31 12 56 44" src="https://user-images.githubusercontent.com/5155373/73537620-33b3f100-4429-11ea-8e20-8ec3c1a82715.png">

Am I missing something?
