### ISSUE TITLE
Invariant Violation: Native module cannot be null.

### ISSUE THREAD

**Issue by Wout-Vanneste-student** [react-navigation/stack#306]
Hi! I'm having an issue. When I try to run my application on my iOS simulator I get an error, everything works fine on my Android device.

But I know what is the cause, it's the package `react-navigation-stack` or `react-navigation-tabs`. They both use the package `react-native-reanimated` which is creating the following error for me.

![image](https://user-images.githubusercontent.com/44393610/70377152-5803bd80-1911-11ea-8623-cd52f2609e81.png)

This is my debug console:

![image](https://user-images.githubusercontent.com/44393610/70377231-3e16aa80-1912-11ea-88d8-e37b69f85619.png)

I have tried everything that was posted here: [#26687](https://github.com/facebook/react-native/issues/26687)

If anyone has any idea how to fix this issue. You would really help me out big time.

**Comment by ralph-dev** [comment]
1. Check if you are using the correct versions for react-navigation across the board, don't mix match
2. Start commenting from root level certain components to trace down the incorrect import/file
All I got tbh, the error is very vague and #2 is, unfortunately, the fastest way to solve it.

**Comment by Wout-Vanneste-student** [comment]
@ralph-dev I'm using the latest versions of each react-navigation, so that shouldn't be the issue.
Right now I really don't have the time to comment out part by part to find out what could be wrong, as I'm working towards a deadline. But if I don't find a better solution I'll do that as I want my application to work on iOS aswel.

**Comment by ralph-dev** [comment]
@Wout-Vanneste-student #2 should only take a few minutes if you are commenting huge blocks at a time at the ROOT.

**Comment by Wout-Vanneste-student** [comment]
I've tried to comment and check all my imports, without luck. Still getting the same error.
This is what my debugger console looks like:

![image](https://user-images.githubusercontent.com/44393610/70387127-7c0edf80-19a1-11ea-97cb-c6adac6aa4bf.png)

It still gives me the warning that I should import `AsyncStorage` from `@react-native-community/async-storage`, even though I have every `AsyncStorage` imported from that package instead of importing it from `react-native`. Even when I unlink some libraries and do a `pod install`, the issue doesn't go away.

**Comment by ralph-dev** [comment]
Can you screenshot your App.js file and index.js file. I need to view just what else is being imported.

**Comment by ralph-dev** [comment]
This same error happened with me I just forgot how i solved it, something to do with commenting the imports out one by one until it stopped erroring, then uncommenting them to trace down the specific library causing issues.

**Comment by Wout-Vanneste-student** [comment]
I found out what went wrong just a few hours ago. I needed to add pods to my podfile and run pod install for some packages. So now working my way up, adding all the packages that I'm using in components that make my app crash, I was able to solve it. Thanks for the help @ralph-dev

**Comment by rwrife** [comment]
I'm having the same issue when I run npx react-native init HelloWorld && cd HelloWorld && $(npm bin)/react-native run-ios

**Comment by parthi22** [comment]
pod 'RNReanimated', :path => '../../../node_modules/react-native-reanimated/RNReanimated.podspec'

I have added reanimated in pods and it is working for me now
