### ISSUE TITLE
[V5] gestureResponseDistance might not be implemented in V5 alpha

### ISSUE THREAD

**Issue by harrisrobin** [react-navigation/stack#309]
Just opening this to confirm that this does not yet work in alpha:

```
 <Stack.Screen
        name="space"
        component={SpaceScreen}
        options={{
          gestureResponseDistance: { horizontal: 500 },
        }}
      />
```

Is this feature planned?

Cheers

**Comment by satya164** [comment]
Stack navigator implements it: https://reactnavigation.org/docs/en/next/stack-navigator.html#gestureresponsedistance

However, you're using native stack, not regular stack. So you should open a feature request for screens: https://github.com/kmagiera/react-native-screens

**Comment by harrisrobin** [comment]
Gotcha, I'll open up a ticket there. Thank you @satya164 !
