### ISSUE TITLE
navigation.replace animation with 2.0.x

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-navigation/stack#325]
With version 2, `navigation.replace` will also animate. I wonder how can I disable the transition animation just for `.replace` calls? I want to keep the animation when doing `.navigate`, but no when replacing. 

Ideally, however, I want the `.replace` call to just animate "backwards". I'm using replace to go to a previous screen which I unmount since it's too heavy. How can I achieve that?

**Comment by cristianoccazinsp** [comment]
Resolved with the following work around: Pass a route param `animate: false` when going to this screen with a .replace call. Then on the screen mount, set it back to true so leaving the screen still animates. Quite hackish if you ask me.

Would it be too hard for `.replace` to receive a "direction" prop or something for the animation?

**Comment by winkelsdorf** [comment]
Same applies for `.reset`. Behavior changed with 2.0.x.

**Comment by satya164** [comment]
> Ideally, however, I want the `.replace` call to just animate "backwards". I'm using replace to go to a previous screen which I unmount since it's too heavy. How can I achieve that?

As of the latest version, you can use `animationTypeForReplace: 'pop'` to achieve it.

https://reactnavigation.org/docs/en/stack-navigator.html#animationtypeforreplace
