### ISSUE TITLE
[Android] [2.0.X] Hiding keyboard is duplicating header size when `android:windowSoftInputMode` is `adjustPan`

### ISSUE THREAD

**Issue by alimek** [react-navigation/stack#326]
Trying to diagnose where is problem, but after updating to `2.0.X`, and updated all breaking changes API when switching screens, header is getting extra height for 1st render, opening `Toggle inspector` looks like is re-rendering card, because header is re-rendered with proper height and can't debug height of it.

My current stack is:

```
container ->
    - stack ->
        -  switch
             - AuthCheck (Component)
             - Login (Component)
             - App (BottomTabNavigator)
        -  lots of modals 
```

It's happening only on Android and only when switching between `Login -> AuthCheck -> App` or `App -> AuthCheck -> Login`.

I am still digging where is problem and try to solve it somehow, but maybe already someone faced similar problem. Will update if will find anything.

**Comment by alimek** [comment]
<img width="500" alt="Screenshot 2020-01-02 at 17 10 40" src="https://user-images.githubusercontent.com/4248465/71677412-1258da00-2d83-11ea-80e2-5b497f9a7b5a.png">

Havent found anything interested, expect that in Layout inspector i can see View which has 200+px height, different behaviour is on Simulator and different in real device.

Simulator getting very small extra height, real device quite heavy one.

**Comment by satya164** [comment]
Can you provide more info? Platform, Android/iOS version, sample code?

**Comment by alimek** [comment]
will try create sample expo app with very basic components and reproduce it and will post it here if any success ;)

**Comment by alimek** [comment]
Hmm cant reproduce this with expo.

In my app found that every time after i focus input, keyboard is presented and every-time header size is doubled.

I have set `android:windowSoftInputMode="adjustPan">` in my app, changing it to `android:windowSoftInputMode="adjustResize">` solving the problem, but its not solution for me 👎 

@satya164 anything in your head that it could be related to anything?

**Comment by satya164** [comment]
Probably related to https://github.com/th3rdwave/react-native-safe-area-context

cc @janicduplessis

**Comment by satya164** [comment]
To test if it's related to safe are context, try passing `safeAreaInsets` in `defaultNavigationOptions`/`navigationOptions`:

```js
defaultNavigationOptions: {
  safeAreaInsets: { top: 24 /* statusbar height */ },
}
```

This should make it work if safe are context is the issue. Don't use this code in production since `24` may not be the correct value depending on platform and version.

**Comment by alimek** [comment]
looks like someone reported it already there: https://github.com/th3rdwave/react-native-safe-area-context/issues/29

**Comment by alimek** [comment]
> To test if it's related to safe are context, try passing `safeAreaInsets` in `defaultNavigationOptions`/`navigationOptions`:
> 
> ```js
> defaultNavigationOptions: {
>   safeAreaInsets: { top: 24 /* statusbar height */ },
> }
> ```
> 

yes, this is fixing problem, would you say, for now:

```
defaultNavigationOptions: {
  safeAreaInsets: { top: StatusBar.currentHeight /* statusbar height */ },
}
```

should be production ready?

**Comment by lorenc-tomasz** [comment]
The same issue. Solution from @alimek helps in some scenarios but still not the perfect solution. @satya164 will you try to fix it as it works OK with 1.x or you will wait until react-native-safe-area-context fix it?

**Comment by satya164** [comment]
It needs to be fixed in `react-native-safe-area-context`. For now you can workaround it by using [`react-native-iphone-x-helper`](https://github.com/ptelad/react-native-iphone-x-helper):

```js
import { getStatusBarHeight } from 'react-native-iphone-x-helper';

// ...

defaultNavigationOptions: {
  safeAreaInsets: { top: getStatusBarHeight(true) },
}

// or

defaultNavigationOptions: {
  statusBarHeight: getStatusBarHeight(true),
}
```

**Comment by satya164** [comment]
Should be fixed with Fix top insets when using pan keyboard mode

**Comment by satya164** [comment]
Should be fixed by https://github.com/th3rdwave/react-native-safe-area-context/commit/f0228a906801d2585460aa77e5bfcebdb8f770fc
