### ISSUE TITLE
Android and stack 2.0.x - keyboard not dismissed

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-navigation/stack#327]
It seem that the keyboard on Android was always dismissed on a screen change with 1.x. However, Android will now keep the keyboard open after a transition. Not sure if this change was intentional, accidental, never designed to work like that, or what. On iOS, the keyboard is always dismissed on screen change.

Should I start adding Keyboard.dismiss calls everywhere?

**Comment by satya164** [comment]
Can you provide a repro?

**Comment by cristianoccazinsp** [comment]
Sorry for the lack of detail, here are the versions.

```
"react": "16.12.0",
"react-native": "0.61.5",
"react-navigation": "4.0.10",
"react-navigation-stack": "2.0.2",
"react-native-reanimated": "1.4.0",
"react-native-screens": "2.0.0-alpha.22",
"@react-native-community/masked-view": "0.1.5",
"react-native-safe-area-context": "0.6.2"
```

Might take me a bit to write a repro, is there a demo repo I can copy?

**Comment by satya164** [comment]
https://snack.expo.io/@satya164/stack-navigation-example

**Comment by cristianoccazinsp** [comment]
https://snack.expo.io/BJ25q62yI

![image](https://user-images.githubusercontent.com/48869228/71727510-3ebf3580-2e19-11ea-8690-d458f21d8bb4.png)

I'm sure this didn't happen with 1.x. Honestly, not a game breaker since I already had some listeners to state/screen change so I can just call dismiss there, but it might bite someone else, and it would be good for it to be consistent with IOS.

**Comment by satya164** [comment]
Should be fixed in latest version
