### ISSUE TITLE
Question in v2 new navigationOptions

### ISSUE THREAD

**Issue by MoeMamdouh** [react-navigation/stack#333]
Hi thank you for this amazing updates in v2
i need to know what are these two props used for:
`TransitionSpecs` and `CardStyleInterpolators`
i think it's not clear in docs, thank you.

**Comment by satya164** [comment]
They can be used for customizing animations for the screen https://reactnavigation.org/docs/en/stack-navigator.html#animations

**Comment by MoeMamdouh** [comment]
@satya164  Yea i already saw this, but i couldn't see changes in animations when i changed the diffrent values of these props  `TransitionSpecs` and `CardStyleInterpolators`
unlike `TransitionPresets` the changes is very clear
