### ISSUE TITLE
Get header height in v2

### ISSUE THREAD

**Issue by AfrazHussain** [react-navigation/stack#335]
Earlier in `v1` there used to be `Header.HEIGHT` to get the height of the header. It doesn't seem to be working in `v2` anymore. I have tried looking at the documentation and source code but couldn't find anything. How to get the height of the header in `v2`?

**Comment by satya164** [comment]
Upgrade to 2.0.7 and then you can use `useFloatingHeaderHeight`/`FloatingHeaderHeightContext`:

```js
const headerHeight = useFloatingHeaderHeight();
```
