### ISSUE TITLE
Unable to resolve module StackGestureContext

### ISSUE THREAD

**Issue by ilya-raevskiy** [react-navigation/stack#338]
<img width="334" alt="Снимок экрана 2020-01-06 в 18 09 13" src="https://user-images.githubusercontent.com/1379392/71820059-c0c88c00-30af-11ea-829f-ce938d4a6028.png">

**Comment by satya164** [comment]
Clear metro cache: if using expo, `expo start -c`, otherwise `react-native start --reset-cache`
