### ISSUE TITLE
headerStyle isn't respected when headerBackground is defined

### ISSUE THREAD

**Issue by mefjuu** [react-navigation/stack#344]
After upgrading to an official v2.x version of Stack, I noticed that headerStyle is no longer applied to the header if headerBackground is passed as well.

**Comment by satya164** [comment]
Please provide a repro along with expected behavior and current behavior.

**Comment by mefjuu** [comment]
You can see it in an official example. E.g.:
https://github.com/react-navigation/react-navigation/blob/master/example/src/StackWithTranslucentHeader.tsx#L235

headerStyle's `borderBottom` isn't visible when it's passed along with custom `headerBackground`. Right now I'm not sure if that behaviour was different in previous versions, but it would be fine if you could check the proper way and correct the examples if needed.

**Comment by satya164** [comment]
If you specify `headerBackground`, you need to add border there. The example is incorrect.
