### ISSUE TITLE
Question: What happened to `isInteraction` ?

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-navigation/stack#347]
1.x had the `isInteraction` prop which could be used to fine tune transitions to screens that would use `runAfterInteractions`. 

2.0.2 seemed to have this value hardcoded to false, or at least transitions would get interrupted midway (e.g., while mounting a camera component that requests a permission)

2.0.12 seem to have changed this again, and now transitions behave as if `isInteraction` is true (that is, `runAfterInteractions` will fire after the screen navigation completes).

Now, I can't seem to get the 2.0.2 behaviour back. I have tried to put `isInteraction` in a variety of places with no luck.

I'm using the following, but `isInteraction` seems to be ignored:

```
const animationConfig = {
  animation: 'spring',
  config: {
    stiffness: 1200,
    damping: 100,
    mass: 3,
    overshootClamping: true,
    restDisplacementThreshold: 0.01,
    restSpeedThreshold: 0.01,
    useNativeDriver: true,
    isInteraction: false
  },
};


transitionSpec: {
  open: animationConfig,
  close: animationConfig,
}

```

Any help please?

**Comment by satya164** [comment]
If you don't want to wait for animations to complete before running you code, why use `runAfterInteractions`?

**Comment by cristianoccazinsp** [comment]
You are right, and I know it's an odd requirement. The screen may have other animations, and the previous behaviour was "tweakable". Nevertheless, I've just adjusted the screens so not everything runs inside the `runAfterInteractions` code in order for it to look more fluid. It would still be great for the previous configurable behaviour to be maintained, was there any reason to remove it?

**Comment by satya164** [comment]
It needs extra code to work which majority of people don't need. Screen transition animations are also badly affected by expensive work such as rendering, so it makes sense to defer work even for screen transitions.

For your use case, you should be able to check if a transition is happening via `navigation.dangerouslyGetParent().state.isTransitioning` and skip running it on `runAfterInteractions`.

**Comment by cristianoccazinsp** [comment]
Thanks for the help! 

Just curious, is the `useNativeDriver` prop also ignored when setting up `transitionSpec` ? Shouldn't animations run smoothly even if there's heavy work on the JS side when that flag is used?

**Comment by satya164** [comment]
Screen transition animations in React Native always use `useNativeDriver`. The reason rendering/re-rendering can affect animations is that rendering happens on the UI thread and animations also happen on UI thread on React Native. In Native apps (on iOS at least), animations don't run on UI that afaik (might be wrong), so it's not a problem there.

**Comment by cristianoccazinsp** [comment]
I guess I was overconfident with this statement from RN; thinking heavy JS work wouldn't affect animations at all.

> Once the animation has started, the JS thread can be blocked without affecting the animation.
https://facebook.github.io/react-native/docs/animations#using-the-native-driver

Anyways, thanks for the help!
