### ISSUE TITLE
error: bundling failed: Error: While trying to resolve module `react-native-safe-area-context` from file

### ISSUE THREAD

**Issue by bhirmbani** [react-navigation/stack#358]
I have installed `react-native-safe-area-context` but it give me this error

```
error: bundling failed: Error: While trying to resolve module `react-native-safe-area-context` from file `/Users/itmi/Documents/itmi-rn/node_modules/react-navigation-stack/lib/module/vendor/views/Stack/StackView.js`, the package `/node_modules/react-native-safe-area-context/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/node_modules/react-native-safe-area-context/src/index.tsx`. Indeed, none of these files exist:
```

**Current Behavior**

running `react-native start`
<img width="564" alt="Screen Shot 2020-01-20 at 14 18 49" src="https://user-images.githubusercontent.com/12825389/72706159-e82f5680-3b8f-11ea-8142-9bf2b4300133.png">

**Expected Behavior**

It should success build

**How to reproduce**

running `react-native start`

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | android
| react-navigation               | 4.0.10
| react-navigation-stack         | 2.0.15
| react-native-gesture-handler   | 1.5.3
| react-native-safe-area-context | ^0.6.2
| react-native-screens           | 2.0.0-alpha.25
| react-native                   | 0.61.5

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/next/troubleshooting.html#im-getting-an-error-unable-to-resolve-module-after-updating-to-the-latest-version

**Comment by bekagaw653** [comment]
https://icetutor.com/question/getting-this-error-error-bundling-failed-error-unable-to-resolve-module-react-native-safe-area-context/

**Comment by bhirmbani** [comment]
for anyone have same problem like me, check following error on above: `However, this package itself specifies a `main` module field that could not be resolved (`/node_modules/react-native-safe-area-context/src/index.tsx`. Indeed, none of these files exist:`

if you have same error, add this on your `metro.config.js` file:
```
resolver: {
    /* resolver options */
   sourceExts: ['jsx','js', 'ts', 'tsx'] // add tsx if its not yet defined
  },
```
then run `npm start -- --reset-cache`
