### ISSUE TITLE
Why Header.HEIGHT is deprecated

### ISSUE THREAD

**Issue by lorenc-tomasz** [react-navigation/stack#360]
Hi,
earlier in v1 there used to be Header.HEIGHT to get the height of the header. Now it seems to be deprecated in favour of useHeaderHeight hook in v2. It's awesome that there will be hook for that but why those that use class components have to create HOC to use it instrad of normal constant?

**Comment by satya164** [comment]
Because header height can change due to a multitude of reasons such as statusbar height, orientation etc. It's not a constant.

You don't have to use a HOC, you can add `static contextType = HeaderHeightContext` and receive the height in `this.context`.

**Comment by satya164** [comment]
It's not a constant, so using it like that can get our of sync from the actual height as cause glitches.

**Comment by yvbeek** [comment]
I can use a closure to provide the height to the stylesheet, unfortunately it can't be based on the context. Could you provide a function that gives the dynamic height value?

Could you also please point me to the source code that handles this?

Thank you.

**Comment by satya164** [comment]
I don't use that library, but you can use props/context like in the scaling example from what I see https://github.com/vitalets/react-native-extended-stylesheet#scaling

Though I would recommend using header height as inline style instead of putting it into stylesheet.
