### ISSUE TITLE
navigation prop changes when calling setParams

### ISSUE THREAD

**Issue by hrastnik** [react-navigation/stack#362]
The `navigation` prop changes unnecessarily when calling `navigation.setParams(...)`. I've provided an Expo Snack to demonstrate the bug.

https://snack.expo.io/@hrastnik/navigation-change-when-setting-param

I expect the navigation prop to remain the same and only the params changing.

This happens with the 

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |  both
| react-navigation               | 4.0.10
| react-navigation-stack         | 2.0.15
| react-native-gesture-handler   | 1.5.0
| react-native-safe-area-context | 0.6.0
| react-native-screens           | 2.0.0-alpha.12
| react-native                   | expo sdk-36.0.0.tar.gz
| expo                           | ~36.0.0
| node                           | any
| npm or yarn                    | any

**Comment by satya164** [comment]
The `navigation` prop contains the params. It's expected behavior. Otherwise your component wouldn't re-render on params change.

**Comment by hrastnik** [comment]
@satya164 Ok, so the solution should be to destructure setParams from the navigation prop.

But the problem persists. We can agree that at least setParams should remain unchanged between re-renders.

Here's an updated Expo snack showing the issue

https://snack.expo.io/@hrastnik/setparam-updating-when-params-are-updated
