### ISSUE TITLE
Do not use forSlide hardcoded if header is hidden

### ISSUE THREAD

**Issue by mo22** [react-navigation/stack#364]
Hi,

the code in `react-navigation-stack@^2.0.15` `src/vendor/views/Header/HeaderContainer.tsx` sets `isHeaderStatic` if the next scene does not have a header.

Later it uses that to override the `styleInterpolator` with `forSlide` if `isHeaderStatic` is set.

However it would be nice if the `navigationOptions`'s `headerStyleInterpolator` property would be used if set, so that for non slide interpolations (in my case I use a slide from bottom) could use `forFade` or other interpolations.

Right now the new scene slides in from the bottom, still the previous's scene floating header slides to the left which does not look good.

```
        const previousScene = self[i - 1];
        const nextScene = self[i + 1];
        const isHeaderStatic =
          (previousScene &&
            previousScene.descriptor.options.headerShown === false &&
            // We still need to animate when coming back from next scene
            // A hacky way to check this is if the next scene exists
            !nextScene) ||
          (nextScene && nextScene.descriptor.options.headerShown === false);

        const props = {
          mode,
          layout,
          insets,
          scene,
          previous,
          navigation:  scene.descriptor.navigation as StackNavigationProp,
          styleInterpolator:
            mode === 'float'
              ? isHeaderStatic
                ? forSlide
                : styleInterpolator
              : forNoAnimation,
        };
```

**Comment by mo22** [comment]
> In next version the header will move up instead of left if you have vertical gesture/animation https://github.com/react-navigation/navigation-ex/blob/67b2ecfcfcf10b2e6c7d1402e044494295a296f0/packages/stack/src/views/Header/HeaderContainer.tsx#L110

That is very much appreciated.

Is there a reason why this is not made configurable?

**Comment by satya164** [comment]
Because there's no reason to if we can do it automatically.

**Comment by satya164** [comment]
Fixed in https://github.com/react-navigation/stack/commit/736209d768994697f94625376afdcc052b35708d

**Comment by mo22** [comment]
Well you can configure custom transitions right now, for example fade between cards or some fancy 3d animation. In all cases the cardStyleInterpolator / headerStyleInterpolator would be called for those except for the case when the header is hidden. So I assume the natural reason for calling the headerStyleInterpolator in the special case of header -> no header is that it is called in every other case already.

**Comment by satya164** [comment]
You can already pass your custom interpolators like `props => <Header {...props} styleInterpolator={/* whatever */} />` which will override whatever interpolator the library passes. I think that's a reasonable alternative if you really need to customize it.
