### ISSUE TITLE
Modal screen in stack with float header

### ISSUE THREAD

**Issue by Bardiamist** [react-navigation/stack#374]
Here is possible way to implent modal screen and keep float header? Card can have overlay by `cardOverlayEnabled` and that is good, I can animate overlay opacity. But I need same for header.

Disappointments:
1. I can't rewrite `styles.content` in `HeaderSegment`
2. I can't to postion title as overlay because of View with `style={{ height: headerStatusBarHeight }}`
3. `styleInterpolator` passed in `header` in `navigationOptions` useless

**Comment by satya164** [comment]
`headerMode: 'float`?

**Comment by Bardiamist** [comment]
Yes, I want keep `headerMode: 'float'` in stack.

**Comment by satya164** [comment]
Then keep it?

**Comment by Bardiamist** [comment]
I need black overlay on the header with opacity.

**Comment by satya164** [comment]
You can wrap the default header and add custom views to add overlay or anything else you want.

**Comment by Bardiamist** [comment]
How I can wrap it? Thanks.

Also feature request: would nice to have availability to not animate header on modal open. (only add overlay and change opacity on transaction). Header should freeze and look like on previous screen.

**Comment by satya164** [comment]
```
<View>
  <Header {...props} />
</View>
```

You can do any animation you want https://reactnavigation.org/docs/en/stack-navigator.html#animations

**Comment by Bardiamist** [comment]
```
<View>
  <Header {...props} />
</View>
```
It's not clear. I don't see any way make this. Where I can get default `Header` compoinent? And where can I transfer wrapped header?
