### ISSUE TITLE
Can't remove bottom border

### ISSUE THREAD

**Issue by CptFabulouso** [react-navigation/stack#378]
I want to remove bottom border of the header. 
The code below used to work in version 1.*, but after upgrading to 2.0.16 it no longer works and I can't find a way to make it work again.

**Current Behavior**

code
```
createStackNavigator(
	{
		someScreen: {
			screen: SomeScreen,
			navigationOptions: () => ({
				headerStyle: {
				           borderBottomWidth: 0,
				},
			}),
		},
	}
)
```

**Expected Behavior**

I expect not to to see border

**Comment by henriquejensen** [comment]
I was having the same problem, because the HeaderBackground adds a box-shadow and you can't remove it (https://github.com/react-navigation/stack/blob/b86e2e6715b1fab516916911166336b5aa69b969/src/views/Header/HeaderBackground.tsx)
so I used the headerBackground property to make my background color
```
 headerBackground: <View style={{ flex: 1, backgroundColor: 'black' }} />,
```

**Comment by CptFabulouso** [comment]
Nice, can confirm this works. Thanks.

I think there could be a prop `headerBackgroundStyle` for simple restyling? @satya164

**Comment by satya164** [comment]
It's not a border. It's a shadow. You should be able to hide the shadow by:

```js
headerStyle: { shadowOpacity: 0, elevation: 0 }
```
