### ISSUE TITLE
cardStyle: { backgroundColor: 'transparent' }  don't work on Android

### ISSUE THREAD

**Issue by Bardiamist** [react-navigation/stack#379]
**Current Behavior**

[Video](https://drive.google.com/file/d/1gZU662HpFVyz4f0ll0D8DNrjuur6F5Op/view?usp=sharing)

**Expected Behavior**

Card on Android should be transparent like on iOS.
Text `Background screen content` should be visible.

**How to reproduce**

On modal screen use `navigationOptions = { cardStyle: { backgroundColor: 'transparent' } }`. Screen should be transparent (you can return null or transparent <View />).

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |Android|
| react-navigation               |4.0.10|
| react-navigation-stack         |2.0.16|
| react-native-gesture-handler   |1.5.3|
| react-native-screens           |2.0.0-alpha.29|
| react-native                   |0.61.5|

**Comment by mefjuu** [comment]
The same here.
But only 2.0.16 is flawed and it wasn't an issue at 2.0.15.

**Comment by satya164** [comment]
If you don't want default animation in Android, you'll need to customize the animation https://github.com/react-navigation/stack/blob/736209d768994697f94625376afdcc052b35708d/example/src/TransparentStack.tsx#L77
