### ISSUE TITLE
How to set the `transitionConfig` method in the API?

### ISSUE THREAD

**Issue by khat33b** [react-navigation/stack#381]
**Current Behavior**

In the previous API, we could set a `transitionConfig` method to the `navigationOptions` of any stack. In the current API, this option does not work. We need this to set a custom transition animation based on the RN Animation API. The new animations given [here](https://reactnavigation.org/docs/en/next/stack-navigator.html#animations) are not robust enough for this.

**Expected Behavior**

There has to be a option to set a custom transition animation based on the RN Animation API.

**How to reproduce**

Try to set a variable named `transitionConfig` method to the `navigationOptions` of a stack. We get a warning that this variable has beeen removed.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android Q
| react-navigation               | 4.0.10
| react-navigation-stack         | 2.0.16
| react-native-gesture-handler   | 1.5.3
| react-native-safe-area-context | 0.6.2
| react-native-screens           | 2.0.0-alpha.22
| react-native                   | 0.62.0-rc.1
| expo                           | NA
| node                           | 13.7.0
| npm or yarn                    | 6.13.6

**Comment by satya164** [comment]
All animations that were possible with old `transitionConfig` are possible with the new APIs. You can use built-in animations or make your own.

https://callstack.com/blog/custom-screen-transitions-in-react-navigation/

**Comment by khat33b** [comment]
@satya164 Thanks for the link. I have been trying out the process mentioned in it. I have added the animation I am trying to convert. While there is an `index` in the new API, there doesn't seem to be an equivalent of `position` which is an `AnimatedValue`. While I have tried using `current` and `next` as such, they have not worked as expected. 
```

cardStyleInterpolator: ({closing, current, index, insets, inverted, next, layouts, swiping}) => {
  return {
    cardStyle: {
      transform: [{
          scale: next ? next.progress.interpolate({
                inputRange: [index - 1, index, index + 1],
                outputRange: [4, 1, 1],
              }) : 1
        }]
    },
    overlayStyle: {
      opacity: next ? next.progress.interpolate({
        inputRange: [index - 1, index - 0.5, index],
        outputRange: [0, 1, 1],
      }) : 1
    }
  };
}
```

Could you please suggest how to proceed?

**Comment by satya164** [comment]
The `current.progress` value represents the `progress` of the screen's animation/gesture which is equivalent to `position`.

> `[index - 1, index, index + 1]`

You don't need to add /remove from `index` with the new API.

Not sure the exact animation you're looking for, but looking at your code, probably something like this

```js
{
  cardStyle: {
    transform: [
      {
        scale: current.progress.interpolate({
          inputRange: [0, 1],
          outputRange: [4, 1],
        }),
      },
    ],
  },
  overlayStyle: {
    opacity: current.progress.interpolate({
      inputRange: [0, 0.5],
      outputRange: [0, 1],
    }),
  },
}
```

You can take a look at the default examples to have more ideas https://github.com/react-navigation/navigation-ex/blob/master/packages/stack/src/TransitionConfigs/CardStyleInterpolators.tsx

It'll also probably be easier to make the animation from scratch rather than trying to port existing `transitionConfig` code.

**Comment by khat33b** [comment]
@satya164 Thanks for the explanation. The animation is basically a zoom-out animation. This code worked properly except there is a slight delay at the end of the animation on closing. I'll try to tweak the values to find the right ones.
