### ISSUE TITLE
[2.0.16][Bug][Android] cardStyle: { backgroundColor: 'transparent' } don't work on Android

### ISSUE THREAD

**Issue by Bardiamist** [react-navigation/stack#383]
**Current Behavior**

Previous screen disappears when transaction animation completed (only on Android).
[Video](https://drive.google.com/file/d/1gZU662HpFVyz4f0ll0D8DNrjuur6F5Op/view?usp=sharing)

**Expected Behavior**

Card on Android should be transparent like on iOS.
Text `Background screen content` should be visible.

**How to reproduce**

On modal screen use `navigationOptions = { cardStyle: { backgroundColor: 'transparent' } }`. Screen should be transparent (you can return null or transparent <View />).

[Example](https://github.com/Bardiamist/react-navigation-bugs/tree/modal)

Don't work even if pass next `cardStyleInterpolator` in `navigationOptions`:
```
  const cardStyleInterpolator = () => ({
    containerStyle: { opacity: 0, backgroundColor: 'transparent' },
    cardStyle: { opacity: 0, backgroundColor: 'transparent' },
    overlayStyle: { opacity: 0, backgroundColor: 'transparent' },
    shadowStyle: { opacity: 0, backgroundColor: 'transparent' },
  });
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |Android|
| react-navigation               |4.0.10|
| react-navigation-stack         |2.0.16|
| react-native-gesture-handler   |1.5.3|
| react-native-screens           |2.0.0-alpha.29|
| react-native                   |0.61.5|

**Previous issue**
https://github.com/react-navigation/stack/issues/379

**I can confirm it is happening only in `2.0.16`. I checked it worked as should in `2.0.15`**

P.S.: @satya164 Please stop giving useless answers and close issues.

**Comment by satya164** [comment]
> Please stop giving useless answers and close issues.

Please stop opening issues without repro if you don't appreciate that I tried to answer your query (that you posted without any extra info to debug) and shared a link to an example of how we use it. You're not going to get your issue looked at by being rude to maintainers.

**Comment by Bardiamist** [comment]
It easy to reproduce and steps provided. Also provided video. Also [confirmed that bug appeared only in 2.0.16](https://github.com/react-navigation/stack/issues/379#issuecomment-578783425)

@satya164 please just don't close issue until the bug is fixed. Otherwise you will discount my efforts. That is not good. I want react-navigation-stack to improve.

**Comment by satya164** [comment]
> It easy to reproduce and steps provided

I have hundreds of issues to look at. No matter how easy it is, creating a repro takes time and I would rather work on things that already have a repro. The code I linked to in the example works fine so I have no idea what your code is supposed to do or the result you expect. The video isn't very useful without any code and without any idea of what do you expect. Maybe the issue is clear to you because you've been trying to achieve something. But I have no idea what that something is.

> please just don't close issue until the bug is fixed. Otherwise you will discount my efforts. That is not good. I want react-navigation-stack to improve

The issue template asks for a repro. If you don't provide a repro, it will become stale and get closed automatically anyway if I don't close it. So please take the time to provide a repro if you actually want it to be looked at.

**Comment by Bardiamist** [comment]
Repro: https://github.com/Bardiamist/react-navigation-bugs/blob/modal/App.tsx

**Comment by satya164** [comment]
You need to specify `mode: 'modal'` https://reactnavigation.org/docs/en/stack-navigator.html#cardstyle

**Comment by Bardiamist** [comment]
No, I don't need this. Think about my screen as partially transparent (not modal).

**Comment by satya164** [comment]
If the docs tell you that you need it and you're making your own decision that you don't need it, then idk what to say.

You definitely need it to prevent the previous screens from detaching as mentioned in the docs.

If you don't want the default modal animation then you can change your animation using the animation API.

**Comment by Bardiamist** [comment]
@satya164 It is very bad. I don't want to specify `mode: 'modal'` for all stack. I need only one transparent ('modal') screen. Should be possible to do it.

And in version `2.0.15` previous screen was not detach. So it was bag? And now that bug still on iOS?

**Comment by satya164** [comment]
Why is that bad? Like I said, you can just change the animation using the `TransitionPresets` if you don't want the default modal animation.

There are literally 2 things it does, prevent screens from detaching and setting the modal animation by default.

**Comment by Bardiamist** [comment]
@satya164 Because I have many screens in my stack and I want to keep `headerMode: 'float'.` for other screens.

**Comment by satya164** [comment]
@Bardiamist you can still specify `headerMode: 'float'`

**Comment by Bardiamist** [comment]
@satya164 Wow, it's nice. I would not be confused if `mode: 'modal'` did not change `headerMode`.
