### ISSUE TITLE
Can it work with react navigation 5.x ?

### ISSUE THREAD

**Issue by i-tengfei** [react-navigation/stack#385]

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/next/upgrading-from-4.x.html

**Comment by i-tengfei** [comment]
@satya164  thanks, any example or help for @react-navigation/stack CardAnimationContext.Consumer with react-native-reanimated?  I tried to make them work together, but failed.

Then I found this release. https://github.com/react-navigation/stack/releases/tag/v2.0.1

> Note: The alpha versions for 2.0 used Reanimated for the animations. We've replaced Reanimated with React Native's Animated API in the stable release. If you did any custom animations with the alpha, please migrate your code to the Animated API.

will react-native-reanimated be supported in the future?

**Comment by satya164** [comment]
> will react-native-reanimated be supported in the future?

Probably, but for now you'll need to use [`Animated`](https://facebook.github.io/react-native/docs/animated) API.
