### ISSUE TITLE
How to get header height in class based component ?

### ISSUE THREAD

**Issue by rahulnainwal107** [react-navigation/stack#388]
I am facing issue in getting header height in class based component. Although there is a solution for functional component but according to my project need, I need it in class based component.
Project details are:
"react": "16.9.0"
"react-native": "0.61.5"
"react-navigation": "^4.0.10"
"react-navigation-stack": "^2.0.15"

**Comment by satya164** [comment]
```js
import { HeaderHeightContext } from 'react-navigation-stack';

// ...

<HeaderHeightContext.Consumer>
  {headerHeight => (
    /* render something */
  )}
</HeaderHeightContext.Consumer>
```

**Comment by rahulnainwal107** [comment]
it's giving me headerHeight 0 when I console it.
