### ISSUE TITLE
headerMode: 'float' broken

### ISSUE THREAD

**Issue by JesperLekland** [react-navigation/stack#396]
**Current Behavior**

When using `headerMode: 'float'` and separate headers on two screens in the same navigator the header from the first screen is shown (weirdly overlaid) on the second.

**Expected Behavior**

You only see one header at a time

**How to reproduce**

Reproducible example in [this snack](https://snack.expo.io/@lekland/headermode-float-bug)

**Use case explanation**

To explain our specific use case. We have a flow (one stack) where the header should be floating (we animate a progressbar within the header), but the last few steps should have a different header. Currently that seems impossible, as on the last steps both headers are rendered simultaneously. 

*Footnote* this was not a problem before upgrading from react-navigation v3

**Comment by satya164** [comment]
If you're using a custom header, you need to implement the animations yourself if you use `headerMode: 'float'`

https://reactnavigation.org/docs/en/stack-navigator.html#header

**Comment by JesperLekland** [comment]
Was this mentioned as a breaking change anywhere? It worked just as one would expect previously. 
Animating between two totally different headers is obviously not the most compelling option. I'm guessing the only workaround is to have parts of the stack in a nested navigator with a floating header and the outer with headerMode: screen? 

PS. Thank you for your work with this library!

**Comment by JesperLekland** [comment]
It seems like this behaviour changed from v1 to v2 of this package.

**Comment by satya164** [comment]
> Animating between two totally different headers is obviously not the most compelling option

Depends on how you animate it. The default animation on iOS for the default header probably matches what you want. You get `scene` prop in your header and you can animate your header the way you want using `scene.progress.current`.

**Comment by JesperLekland** [comment]
> > Animating between two totally different headers is obviously not the most compelling option
> 
> Depends on how you animate it. The default animation on iOS for the default header probably matches what you want. You get `scene` prop in your header and you can animate your header the way you want using `scene.progress.current`.

Well the problem are the screens at the end of the flow, the look *completely* different. 
And with [this example](https://snack.expo.io/@lekland/paranoid-croissant) it seems impossible to have two different headers without rendering them both at the same time (please correct me if I'm wrong)?

Also the progress we're animating is something different, basically the users progress through the flow (e.g 1/10 steps)

**Comment by satya164** [comment]
> And with this example it seems impossible to have two different headers without rendering them both at the same time (please correct me if I'm wrong)?

You can translate the inactive header out of the screen using `translateX` or `translateY` depending on the animation you want, or change opacity `0` so that 2 headers aren't visible at the same time. It's upto you to customize the effect you're looking for.

Something like:

```js
const translateX = scene.progress.current.interpolate({
  inputRange: [0, 1],
  outputRange: [headerWidth, 0],
});
```

**Comment by JesperLekland** [comment]
> > And with this example it seems impossible to have two different headers without rendering them both at the same time (please correct me if I'm wrong)?
> 
> You can translate the inactive header out of the screen using `translateX` or `translateY` depending on the animation you want, or change opacity `0` so that 2 headers aren't visible at the same time. It's upto you to customize the effect you're looking for.
> 
> Something like:
> 
> ```js
> const translateX = scene.progress.current.interpolate({
>   inputRange: [0, 1],
>   outputRange: [headerWidth, 0],
> });
> ```

That could indeed work, in our case it would probably amount to a total mess in the code though. Thanks for the suggestion though. Will give nested navigators a try to simplify the logic

**Comment by JesperLekland** [comment]
Update: The animation actually worked out alright, although it's not the most intuitive solution. Thank you @satya164 for your help.

PS. I think this change in behaviour should be mentioned in the changelog of v2 👍
