### ISSUE TITLE
How to use ModalPresentationIOS with nested stacks

### ISSUE THREAD

**Issue by aymanosman** [react-navigation/stack#410]
# Problem
I am trying to use the newer `ModalPresentationIOS` transition with an app that uses nested stacks. I've produced a minimal example [here](https://gist.github.com/aymanosman/404b446bc3650381b48de2cf3728b272).

The bad effect that I'm seeing is shown in the gif below. The overlay effect is happening twice, when I would like it to happen once.

![out](https://user-images.githubusercontent.com/3605049/74146948-1d145380-4bfa-11ea-9a96-574c495700ec.gif)

**Comment by tapz** [comment]
I'm also seeing this kind of effect. The screen slider from the bottom nicely but stays for a while below the top of the screen and is then stretched to full screen. Looks like really bad. Why doesn't the transition go smoothly from bottom to top and why is there a tab below the screen when I'm using reset not push? This is not how the modal transition works in native iOS.

**Comment by satya164** [comment]
Nesting navigators works just like regular react components. If you nest 2 views like this, you'll see same effect of each view having its own background and border:

```js
<View
  style={{
    backgroundColor: 'tomato',
    borderColor: 'black',
    borderWidth: 10,
    padding: 10,
  }}>
  <View
    style={{
      backgroundColor: 'tomato',
      borderColor: 'black',
      borderWidth: 10,
      padding: 10,
    }}
  />
</View>
```

When you're nesting navigators, you see the same effect.

There's no reason 2 nest 2 navigators here. Just use a single navigator. https://reactnavigation.org/docs/en/nesting-navigators.html#best-practices-when-nesting
