### ISSUE TITLE
react navigation v3.0.0-alpha.14 android  when screen has dark background  the  fadein and fadeout animation flickering 

### ISSUE THREAD

**Issue by gaodeng** [react-navigation/stack#47]
Here is the video show this issue.

https://www.youtube.com/watch?v=TrMWhvNbLb4

**Comment by brentvatne** [comment]
@gaodeng - did this happen on 2.x also?

**Comment by gaodeng** [comment]
@brentvatne Hi,this happen on 2.x too.
It seems add  needsOffscreenAlphaCompositing to the opacity view can fix it.but the docs says that is extremely expensive.https://facebook.github.io/react-native/docs/view#rendertohardwaretextureandroid

**Comment by brentvatne** [comment]
interesting. can you create a minimal reproducible example? https://stackoverflow.com/help/mcve

**Comment by gaodeng** [comment]
@brentvatne  Hi,here is the example reproduce the issue
https://github.com/gaodeng/react_navigation_stack_transition_bug

**Comment by andresesfm** [comment]
@miblanchard did you mean this other issue instead: https://github.com/kmagiera/react-native-screens/issues/35

**Comment by mikeyamato** [comment]
JFYI, while I'm not using React Navigation Stack, I am experiencing the same white flash issue with React Navigation v3.0.9. Only on Android. iOS performs without issue. This happens when I advance forward to the next screen as well as going back to a previous screen.
