### ISSUE TITLE
Why 8 character limit on back button titles?

### ISSUE THREAD

**Issue by SteffeyDev** [react-navigation/stack#48]
I noticed in the code that even if a back title could fit based on the calculated dimensions, you still default to the truncated title if the back title length > 8 characters long.  This seems strange, because the width calculations should be sufficient to determine whether to use the back button button title or truncated back button title.

I’m especially concerned with usage on Tablets, where you could fit a large amount of text in the back button title and still fit comfortably.  I’d be fine making a PR that just bypasses this I character limit on tablets only, but why have the limit at all if you are doing width-based calculations?

**Comment by brentvatne** [comment]
It's an arbitrary limit that works well in many situations, we haven't had a chance to revisit yet. Width calculations are asynchronous whereas we know text length immediately

**Comment by SteffeyDev** [comment]
Ok, sorry for not being more specific, the bug is that on Tablets, where there is plenty of space, I expect it to usually not truncate the back button text, whereas right now it almost always truncates my back button text.

**Comment by brentvatne** [comment]
right, it's useful still in a new issue to provide an example and compare it to what you would expect from the built-in equivalent on ios and android

**Comment by satya164** [comment]
Is this still relevant? I couldn't find any code which checks if the back button label is more than 8 characters long.

I'm closing it for now.
