### ISSUE TITLE
Request: API to get information if there is any place to go back

### ISSUE THREAD

**Issue by dzek69** [react-navigation/stack#55]
Hi,

I wanted to have two buttons on the left part of header, default back button + my custom button.
However, overriding `headerLeft` causes default back button not to be rendered.
I wanted to duplicate it and it's behavior to not be visible if there is no screen to pop from the history stack, but there is no way to know how big is history stack. As I can see [here](https://github.com/react-navigation/react-navigation-stack/blob/46b67c7bca596b3c75f33ff86ce6ec0625a8708e/src/views/Header/Header.js#L190) - you're using informations that are not exposed on any public API.

And my request is to expose it in the `navigation` prop.

**Comment by satya164** [comment]
Now you should be able to do `navigation.isFirstRouteInParent()` to check if the screen is the first in the stack: https://github.com/react-navigation/core/commit/0cc8f9e968f6d0bd3ebc8130268ec7f451639dfd

**Comment by mohmdalfaha** [comment]
@satya164 Hi, I am trying to use this ```navigation.isFirstRouteInParent()``` but I am getting 
```
TypeError: TypeError: navigation.isFirstRouteInParent is not a function. (In 'navigation.isFirstRouteInParent()', 'navigation.isFirstRouteInParent' is undefined)
```
