### ISSUE TITLE
React Native test with Jest - TypeError: Cannot read property 'BaseButton' of undefined

### ISSUE THREAD

**Issue by sidhijakpat** [react-navigation/stack#72]
I'm using react native with react navigation, and react navigation stack,

when trying to test using `npm test` with `jest`, I got this error message

```
Test suite failed to run

    TypeError: Cannot read property 'BaseButton' of undefined

      at Object.BaseButton (node_modules/react-navigation-stack/dist/views/BorderlessButton.js:6:61)
      at Object.<anonymous> (node_modules/react-navigation-stack/dist/views/TouchableItem.js:13:1)
      at Object.<anonymous> (node_modules/react-navigation-stack/dist/views/Header/HeaderBackButton.js:4:1)
```

here is my package.json dependencies:
```
"dependencies": {
    ...
    "native-base": "^2.8.1",
    "react": "^16.6.3",
    "react-native": "^0.57.5",
    "react-navigation": "^3.0.1",
    "react-navigation-stack": "^1.0.2",
    "react-redux": "^5.1.1",
    "redux": "^4.0.1",
    ...
  },
  "devDependencies": {
    ...
    "@babel/core": "^7.1.6",
    "babel-jest": "^23.6.0",
    "babel-preset-react-native": "^4.0.1",
    "jest": "^23.6.0",
    "metro-react-native-babel-preset": "^0.49.2",
    "react-test-renderer": "^16.6.3",
    ...
  },
  "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "/node_modules/(?!native-base)/"
    ]
  }
```

what did I do wrong?

Any help will be appreciate

Thank you

**Comment by sidhijakpat** [comment]
forget to add, here is the content of `app.test.js` test file

```
import React from 'react';
import App from '../App';

import renderer from 'react-test-renderer';

jest.mock('react-native-camera', () => 'Camera');
jest.mock('react-native-gesture-handler', () => {});

test('renders correctly', () => {
  const tree = renderer.create(<App />).toJSON();
  expect(tree).toMatchSnapshot();
});
```

**Comment by sidhijakpat** [comment]
I haven't try this again, since there are some work coming, 

but I think you need to add `Header` inside  your mock,
maybe like so

`jest.mock('react-navigation-stack', () => {
     Header: {}
});`

**Comment by grigorigoldman** [comment]
Is there a solution to this issue? I've just upgraded to `react-navigation` 3.11.0 and started getting this error when running my tests.

```
Test suite failed to run

    TypeError: Cannot read property 'BaseButton' of undefined

      at Object.<anonymous> (node_modules/react-navigation-stack/lib/commonjs/views/BorderlessButton.tsx:5:1)
      at Object.<anonymous> (node_modules/react-navigation-stack/lib/commonjs/views/TouchableItem.tsx:19:1)
      at Object.<anonymous> (node_modules/react-navigation-stack/lib/commonjs/views/Header/HeaderBackButton.tsx:12:1)
```

Here's an extract from my package.json:
```
"dependencies": {
  ...
  "react": "^16.8.3",
  "react-dom": "^16.2.0",
  "react-native": "^0.59.8",
  "react-navigation": "^3.11.0",
  ...
}
```

Mocking `react-navigation-stack` lead to other problems, so it didn't really work for me...

**Comment by strdr4605** [comment]
@brentvatne Is there an update for this issue?

**Comment by wongcoder** [comment]
You have to mock it. The above doesn't work as it's missing a return statement. 
This is a working version: 
```jest.mock('react-navigation-stack', () => { return {Header: ()=>'whatever'} });```

This is ES6 syntax, as ```()=>'something'``` is shorthand for ```()=>{ return 'something' } ```.

**Comment by brentvatne** [comment]
`BaseButton` comes from react-native-gesture-handler, have you tried this? https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html#testing

**Comment by satya164** [comment]
Closing since this is from a third party lib and not react-navigation-stack
