### ISSUE TITLE
transparentCard: true doesn't work on Android

### ISSUE THREAD

**Issue by todorone** [react-navigation/stack#95]
It works perfectly on iOS, but on Android the screen under modal is just being hidden.
Reproduce: https://snack.expo.io/S1ZKx1VvV

**Comment by todorone** [comment]
@brentvatne Maybe there is some kind of workaround to implement popups with previous screen visible? It's the only critical issue that block from upgrading `react-navigation` from `v2` to `v3`(second version works perfectly on both platforms).

**Comment by brentvatne** [comment]
hey @todorone! i don't have time to investigate this right now, could you give it a shot and let me know what you find?

**Comment by todorone** [comment]
@brentvatne Thanks for response. This is the screenshot of the problem:
<img width="822" alt="Screen Shot 2019-03-14 at 7 35 28 AM" src="https://user-images.githubusercontent.com/423701/54334120-a52a5b80-462d-11e9-8a82-ff21fd2e1a18.png">

So basically we have previous stack hidden on Android and visible on iOS when we navigated to stack with `transparentCard: true`. I don't know how to check if `useScreens()` has been activated(I'm using expo), but if it's enabled by default, maybe root of this issue is somehow connected with incorrect `react-native-screens` behavior - https://github.com/kmagiera/react-native-screens/issues/61 Otherwise I guess there is no reason for different behavior on iOS and Android of the same JS code.

**Comment by todorone** [comment]
@brentvatne Just tested on blank react-native 0.59 install, without `react-native-screens`, same result, so the problem is not there. Interesting that the previous screen is visible when animation of popup appear is executing and as soon as it finished, previous screen is being hidden.

**Comment by todorone** [comment]
@brentvatne I was able to settle down bug. The problem is that `forFadeFromBottomAndroid` from `StackViewStyleInterpolator.js` does not work with `transparentCard: true` Cards. Due to final `opacity` of animated interpolator is `0`, background card is becoming invisible. If we switch from `forFadeFromBottomAndroid` to iOS default `forVertical`, everything's work perfect. I'm not completely sure why we have `0` as final opacity value, so not sure where to go next... 😸 

Current workaround for me is adding undocumented `screenInterpolator: () => {}` to `createStackNavigator`'s config.

**Comment by brentvatne** [comment]
maybe `transparentCard` should change the stack animation to no animation

**Comment by todorone** [comment]
@brentvatne Either change animation to no animation(but it will breaking change) or set unified animation to `forVertical` for both iOS & Android platforms - it is more like bugfix to current behavior.

**Comment by brentvatne** [comment]
i'm ok with changing it to no animation without a major version bump because this is marked in the docs as experimental:

> transparentCard - *Experimental* - Prop to keep all cards in the stack visible and add a transparent background instead of a white one. This is useful to implement things like modal dialogs where the previous scene should still be visible underneath the current one.

**Comment by euroclydon37** [comment]
Running into this right now, and I would definitely vote to have the same defaults across ios/android.

**Comment by brentvatne** [comment]
PR welcome as mentioned above

**Comment by todorone** [comment]
@brentvatne Please take a look if this PR makes sense...
